### ISSUE TITLE
Matplotlib inside a pl exercice

### ISSUE THREAD

**Issue by nborie** [PremierLangage/premierlangage#104]
I want to produce an exercise which has the following behavior...

It generate a random move of an object which give its position each second. At the end, I recover a list of 2d points which give an idea of how the object is moving.

The student must say if the move is uniform linear motion.

I can generate 2d points and nice matplotlib graphic displaying the motion. I did not manage to insert a matplotlib plt inside a pl exercise.

**Comment by qcoumes** [comment]
I never used matplotlib. What kind of file is a plt ? An image ?

**Comment by nborie** [comment]
matplotlib is currently THE small and efficient python lib to generate graphics. On linux, we used to use gnuplot but gnuplot is old, not sexy and generate ugly (but efficient) graphs.

matplotlib is up to date, more sexy, flexible, very light and efficient. Today, math teacher who love computers use this lib. plt is a construction inside the matplotlib library. Matplotlib is so much standard that it is already installed on pl-test (D.R. did test it...).

That being said, I did not manage to include matplotlib inside pl. I did see that on the web : http://mpld3.github.io/

The questions are : 
* Do we need matplotlib ? (or another lib, I do not kwon... )
* Do we need mpld3 ? 
* Someone know a better way to go from Python code to graphic inside a browser and the solution is ...... 

My guess is that matplotlib is the better option. But it is only my guess...

**Comment by nimdanor** [comment]
D3js could be the tool we use for graphics in the statistics module.

**Comment by nthiery** [comment]
>    D3js could be the tool we use for graphics in the statistics module.

And possibly the resolution between matplotlib (for easy Python
integration) and d3 (for nice interactive visualization in the
browser) is [mpld3](https://mpld3.github.io/)

In case PL gets close enough to Jupyter, another alternative is
[bqplot](https://bqplot.readthedocs.io/).

**Comment by esandier** [comment]
I tested matplotlib in a pl exercise here
[choose pretty plot](https://pl.u-pem.fr/filebrowser/option?name=test_pl&path=Yggdrasil/maths-pl-bank/exercises/plots/graph.pl)
It uses the template mathplotlib.pl
I dont know if it is of any help.

**Comment by mciissee** [comment]
Closed due to inactivity
