### ISSUE TITLE
Affichage du taux de réussite d'un exercice

### ISSUE THREAD

**Issue by magdalena-kobylanski** [PremierLangage/premierlangage#108]
Use case : on a un QCM avec n questions en amphi, tout le monde répond à partir de son téléphone, je voudrais avoir un affichage rapide : 

Première étape : affichage  n réponses reçues (dynamique)

lorsque le prof le décide 
Deuxième étape : affichage graphique du taux de réponse.
A XX 10%
B XXXXXXX40%
C XXXXXXXXXX 60%
D X 5%

Troisième étape discussion : re vote  (ou affichage des bonnes réponses)

reaffichage  n réponses reçues (dynamique)

A XXXXXXXXXX 70%
B XXX15%
C XX 10%
D X 5%

Quatrième étape : affichage des bonnes réponses (code couleur)

**Comment by qcoumes** [comment]
N'est-ce pas ce que [Socrative](https://www.socrative.com/) fait ?

**Comment by nimdanor** [comment]
Ça a l’air bien.
On peut le faire avec PL ?
