### ISSUE TITLE
No email from the platform

### ISSUE THREAD

**Issue by plgitlogin** [PremierLangage/premierlangage#109]
No email and credentieals from the platform.
Should ask the CRI for algorithm of password creation.

**Comment by qcoumes** [comment]
What ?

**Comment by plgitlogin** [comment]
When you connect the first time on the plateforme (PL) you are presented with a text telling you that a email was send to your email adresse with credentials to login directly on the plate form.
Two solutions : 
- no more text and no direct login 
- that the email with credentials is effectively send
