### ISSUE TITLE
Choice of input mecanisme for math

### ISSUE THREAD

**Issue by plgitlogin** [PremierLangage/premierlangage#110]
The site mathquill.com permit to create input field of math elements.
There is even a graphical contruction "a la" graphical latex.

Could you make a survey of those technologies so we can choose one for the project.

links: 
mathquill.com
symbolab.com

**Comment by esandier** [comment]
1) Regarding MathQuill, I checked it out last year and wrote an email to the maintainers to ask if there was Documentation in April 2018, but they never answered.  I am afraid it is no longer maintained.

It basically allows to type Latex code and have it displayed Wysiwyg on the fly. This requires to know at least some Latex commands but not all. The thing behaves very nicely.


2) Symbolab.com is not an equation editor, rather it is an e-learning site which uses an equation editor to enter answers. The editor is of a type often encountered where you click on symbols and to construct the equation.

3)  By Googling "javascript equation editor", i came up with a list of those at 
https://github.com/mathjax/MathJax-docs/wiki/List-of-web-based-math-editors

From the list I checked:

- CKeditor, but i do not understand how it works very well, it seems to be very flexible.

- http://camdenre.github.io/src/app/html/EquationEditor. A wysiwyg editor very simple for inputting math.

- https://guppy.js.org/site/examples/basic/  Is very similar to MathQuill it seems. 

- http://visualmatheditor.equatheque.net/index.html Again looks like a very flexible solution, but I dont know how easy it is to embed.

- https://mathscribe.com/author/jqmath.html Does not seem to offer the possibility of wysiwyg input, t is more like a variant of mathjax, but it seems possible to include input fields in the equations, which is a big plus.

**Comment by plgitlogin** [comment]
@mciissee  can you look at the list proposed by etienne and give you opinion on the simplicity of integrating each solution in the plateform.

**Comment by mciissee** [comment]
@plgitlogin of course I'll look into it.

**Comment by ddoyen** [comment]
And what about MathLive ?

https://mathlive.io/deploy/index.html

- Nice rendering
- WYSIWYG
- Versatile and easy input mechanism (allowing inline shortcuts, keystroke shortcuts and virtual keyboards).
- It generates in the end an expression in Latex (which could be easily converted to a sympy expression for the analysis of the answer) or in a JSON-like format.
- Documented and is still active.
- Licensed under the [MIT License](https://github.com/arnog/mathlive/blob/master/LICENSE.txt).

**Comment by esandier** [comment]
Looks great, I missed this one.
Etienne
    Le ‎samedi‎ ‎26‎ ‎janvier‎ ‎2019‎ ‎21‎:‎34‎:‎52‎ ‎CET, ddoyen <notifications@github.com> a écrit :  
 
 
And what about MathLive ?

https://mathlive.io/deploy/index.html
   
   - Nice rendering
   - WYSIWYG
   - Versatile and easy input mechanism (allowing inline shortcuts, keystroke shortcuts and virtual keyboards).
   - It generates in the end an expression in Latex (which could be easily converted to a sympy expression for the analysis of the answer) or in a JSON-like format.
   - Documented and is still active.
   - Licensed under the MIT License.

**Comment by nimdanor** [comment]
I am pretty dumb so i need some information on:
 > - It generates in the end an expression in Latex (which could be easily converted to a sympy expression for the analysis of the answer) or in a JSON-like format.

How do you get this expression in json or in python sympy/numpy/else ???
I don't know how to do the "easily" part ?

**Comment by esandier** [comment]
Indeed that was a bit optimistic. There is, though, a Latex2Sympy project on GitHub, but it does not seem to be active, files date 2 years back. 
As an alternative, Mathlive produces in fact an abstract syntax tree, they give an example where expressions entered are parsed then then evaluated with mathjs, but I did not look at it closely https://mathlive.io/deploy/examples/mathjs/
Maybe it is possible to use this output more effectively than latex output?
Etienne    Le ‎lundi‎ ‎28‎ ‎janvier‎ ‎2019‎ ‎14‎:‎03‎:‎49‎ ‎CET, Dominique Revuz <notifications@github.com> a écrit :  
 
 
I am pretty dumb so i need some information on:

   
   - It generates in the end an expression in Latex (which could be easily converted to a sympy expression for the analysis of the answer) or in a JSON-like format.


How do you get this expression in json or in python sympy/numpy/else ???
I don't know how to do the "easily" part ?

**Comment by ddoyen** [comment]
You're right.

There is a Latex parser in sympy but this is probably not the safest and most robust way to handle the answer.

> LATEX parsing was ported from latex2sympy. While functional and its API should remain stable, the parsing behavior or backend may change in future releases.
> 
> The current implementation is experimental. The behavior, parser backend and API might change in the future. Unlike some of the other parsers, LATEX is designed as a type-setting language, not a computer algebra system and so can contain typographical conventions that might be interpreted multiple ways.

https://docs.sympy.org/latest/modules/parsing.html

Using the syntax-tree JSON format is probably better.

http://docs.mathlive.io/tutorial-MASTON.html

**Comment by nthiery** [comment]
Yeah, latex is a pretty painful thing to parse, and it's likely that
the structure/semantic will be lost in the process. IIRC from reading
the mathlive site, it said it could also export to MathML which is a
much better bet. We don't quite have a mathml input in e.g. SageMath,
getting one that works reasonably for a range of typical inputs should
be fairly straightforward. We have some support for openmath though:

        https://github.com/OpenMath/py-openmath

**Comment by ddoyen** [comment]
Here is a demo of a PL exercise with MathLive.

https://github.com/PremierLangage/conceptexo/tree/master/MathLive

The exercise displays a MathLive input field (with a virtual keyboard) and gets the answer in an abstract syntax tree.

Small bug: when I launch the exercise in test mode (with the button in the file manager), it works ; when I launch in preview mode (with the button above the script editor), it doesn't work.

**Comment by mciissee** [comment]
@ddoyen the preview mode bug should be fixed now on https://pl-preprod.u-pem.fr/filebrowser

**Comment by esandier** [comment]
This is related to the issue, although it does not exactly  adress it.

I came upon this question at StackOverflow, 
[https://stackoverflow.com/questions/21171107/mathjax-rendering-html-input-fields-in-mathml]()
From which I deduce that 
1) It is possible to include input fields in MathML script, hence to write equations to be user-completed. Maybe a parser could translate simple enough Latex with input fields to MathML code which could be included in `form`.
2) It is somewhat infered from the answer to the question that MathJax will eventually allow this too, but doesn't because it is based on an earlier version of MathML, which did not allow it.

**Comment by nimdanor** [comment]
@esandier and @ddoyen can i close this ??
the components system solves this issue ?

**Comment by ddoyen** [comment]
Yes !
