### ISSUE TITLE
Deep linking

### ISSUE THREAD

**Issue by plgitlogin** [PremierLangage/premierlangage#119]
Dans les sécpfication de lti il y a la possiiblité de selectionner une ressource dans le lti-producteur 
grace au message  "Content-Item" quand on ajoute une ressource dans le lti-client (moodle pour nous).

Question combien de temps pour implémenter cette fonctionnalité ?

**Comment by qcoumes** [comment]
I'm not sure I get you meant, *content-item* (now called "**Deep Linking**") is used to get a ressource from the TP (Premier Langage) to the TC (Moodle), not the other way.

Why would we need this ?

**Comment by plgitlogin** [comment]
We need this because the way we put activity on moodle is very bad !!!!
We need a way to be able to choose in a liet of activity what we whan to add to a course.

**Comment by qcoumes** [comment]
I'll look into this, it seems that LTI links are part of ressources that can be created through Deep Linking.

We'll also have to cehck whether Moodle is compatible with it.
