### ISSUE TITLE
Sandbox timeout when compiling C++

### ISSUE THREAD

**Issue by nthiery** [PremierLangage/premierlangage#126]
I am upgrading my C++ exercises to the new PL API and am stuck debugging it. The sandbox times out at the stage where `g++` is run. I don't see why a basic compilation should take that much time. To be able to analyse further, is there a way to temporarily raise that timeout? I see that this can be configured in the sandbox code, but unless I run my own server, I don't have control on that.
Could this be controlled instead from a PL script?

Help most welcome, as I would like to finally put the exercises in production as soon as possible.
The exercise is available from:

https://pl.u-pem.fr/filebrowser/home/cpp-info111/exercices/test/opt/?option=entry-direct-edit_pl&target=output.cpp.pl

It gets stuck line 84 of https://pl.u-pem.fr/filebrowser/home/cpp-info111/template/opt/?option=entry-direct-edit&target=graderCpp.py

**Comment by qcoumes** [comment]
Sadly we can't see any of your personnal file located in your *home/*. You may have to push your files on a public repository to make them visible.

As for the time out, it may be caused by an excessive usage of RAM, which slows the sandbox considerably. I don't know how much the IT department gave to the sandbox, but it's probably around 50Mo, which is enough to execute code, but may need to be increased for compilation.

I'll check this with them on monday.

**Comment by nthiery** [comment]
>    Sadly we can't see any of your personnal file located in your
>    home/. You may have to push your files on a public repository to
>    make them visible.

It's a clone of https://github.com/PremierLangage/cpp-info111, with
some tracing info added.

>    As for the time out, it may be caused by an excessive usage of RAM,
>    which slows the sandbox considerably. I don't know how much the IT
>    department gave to the sandbox, but it's probably around 50Mo, which is
>    enough to execute code, but may need to be increased for compilation.

Thanks for the feedback. Indeed, 50Mo is not much. For the record, it
used to work back in September; so if that's the cause, some of the
configuration must have changed. Also the program being compiled is
not much more than a hello world.

**Comment by qcoumes** [comment]
I did some test using your repo :
```
[2018/11/18 12:03:19] DEBUG -- Execution of evaluate with parameters DOCKER_MEM_LIMIT=400m and DOCKER_CPUSET_CPUS=0 took 0.4715230464935303 secondes.

[2018/11/18 12:05:13] DEBUG -- Execution of evaluate with parameters DOCKER_MEM_LIMIT=40m and DOCKER_CPUSET_CPUS=0 took 2.3614954948425293 secondes.
```

Taking into account that I'm running on an high-end CPU and a SSD, it seems 40Mo and 400Mo of RAM still make a huge difference of speed, I'll see with the IT department to increase the RAM (it won't be 400, but should still be enough).

I also made some changes to graderCpp.py to reduce RAM usage (still not enough for PL) and fixed a typo in wims.pl (I did a pull request).

**Comment by nthiery** [comment]
On Sun, Nov 18, 2018 at 04:16:59AM -0800, Coumes Quentin wrote:
>    I did some test using your repo :
> [2018/11/18 12:03:19] DEBUG -- Execution of evaluate with parameters DOCKER_MEM_
> LIMIT=400m and DOCKER_CPUSET_CPUS=0 took 0.4715230464935303 secondes.
> 
> [2018/11/18 12:05:13] DEBUG -- Execution of evaluate with parameters DOCKER_MEM_
> LIMIT=40m and DOCKER_CPUSET_CPUS=0 took 2.3614954948425293 secondes.
> 
>    Taking into account that I'm running on an high-end CPU and a SSD, it
>    seems 40Mo and 400Mo of RAM still make a huge difference of speed, I'll
>    see with the IT department to increase the RAM (it won't be 400, but
>    should still be enough).

Thanks for testing, and for checking this out with the IT department.
I ran g++ under /usr/bin/time on all the programs of the exercise, and
the memory used oscillated between 40M and 60M. So yeah, having 100M
would be nice.

>    I also made some changes to graderCpp.py to reduce RAM usage (still not
>    enough for PL) and fixed a typo in wims.pl (I did a pull request).

Thanks for the code review!

**Comment by nthiery** [comment]
Out of curiosity, I just made a quick check with `clang++`: it tends to use a bit less memory (40-47Mo).
Usually the error messages are slightly better. So we may consider switching to that (if/when clang will be available in the docker image).

**Comment by nthiery** [comment]
Just for info: I'll have some time this afternoon to work on the exercises. If the memory limit could be resolved by then, that would be great. Thanks in advance!

**Comment by qcoumes** [comment]
It should be updated by 14h30.

**Comment by nthiery** [comment]
>    It should be updated by 14h30.

Excellent. Thanks!

**Comment by qcoumes** [comment]
As planned, we upgraded the sandbox from 20Mo to 100Mo, and from 2 cpu core to 4.

Can you now compile your exercise ?

**Comment by nthiery** [comment]
Salut Nicolas,

>    [1]@nthiery You should give a look at what have been done on
>    [2]https://github.com/nborie/Cbank . It is not c++ but C 89 (and I
>    really want to keep this 89 standard), you have a lot of different kind
>    of exercises (using codebefore, codeafter, preprocesseur, a programm, a
>    function, expected outputs, code given by teacher, ....).

Yes indeed! I am keeping an eye on it. I like in particular the
compilation error reporting :-)

I wanted to port our collection of WIMS exercises with minimal
changes: there is something to be said about the input format we use
to crowd source the authoring to our teaching teams. Nevertheless, 90%
of the underlying code in cpp-info111 and CBank is very similar and
should eventually be shared.

It would not take much to adapt that code from Cbank to match my
needs; basically a bit of abstracting away the API; but that takes
some discussion which is best done face to face.

I opted for the strategy of rewriting the code for now to:

- solve ASAP my need
- learn the framework
- think about the correct abstraction

But that's just experimental code that I'll happily discard. I am
looking forward a joint sprint to this end! Sometime next Spring?


Btw: we should similarly sprint on merging our code about harmonic modules :-)

Amitiés,
