### ISSUE TITLE
Is   =% documentation correct ?

### ISSUE THREAD

**Issue by nimdanor** [PremierLangage/premierlangage#131]
In the doc =% is not finish with a == 
it's a bug or a feature ??

**Comment by nimdanor** [comment]
home:/dossier1/exo1.pl a encore du sens ??

je suis sur la doc de PL.u-pem.Fr

**Comment by qcoumes** [comment]
> home:/dossier1/exo1.pl a encore du sens ??

D'après le diagramme, Oui
![pathv2](https://user-images.githubusercontent.com/24588090/48782473-91559500-ecde-11e8-876d-a9dc1ba63231.png)

**Comment by Pavell94000** [comment]
It's actually %=
data
==

Documentation is fixed for 0.5.0

**Comment by qcoumes** [comment]
I was wondering if it would not be better to be `=%`, in order to allow an implementation of `+=%` (operation corresponding to Python's `d1.update(d2)` or `d1 = {**d1, **d2}`) while remaining coherent with other `+` operator (namely `+=` and `+=@`) ?
