### ISSUE TITLE
No latex in exercise feedback

### ISSUE THREAD

**Issue by ddoyen** [PremierLangage/premierlangage#134]
Latex expressions (within delimiters $%..%$) in the feedback string passed to the grader "evaluator" do not seem to be processed. They are left raw when the exercise is played.

**Comment by nborie** [comment]
Could you provide a link or something allowing others to reproduce the behavior ? This is probably a bug but I cannot easily confirm (I should have to write an exercise with some latex inside the feedback and hope I inserted the right latex that produce the bug...).

Perhaps you could just copy-paste your exercise here but it is perhaps not enough ? I don't know, it depends on the feedback module you are using and so much things around it...

**Comment by mciissee** [comment]
Linked to #198 and fixed
