### ISSUE TITLE
How to define a CSS in a pl exercise ?

### ISSUE THREAD

**Issue by ddoyen** [PremierLangage/premierlangage#137]
Is there a way to define a CSS in a pl exercise ? Something like the definition of an external CSS in the head section of an HTML page ?

If there is nothing implemented yet, it could be defined by adding a key "CSS" in the pl file.

**Comment by nimdanor** [comment]
Not so easy, we want a css only for the div of the exercice so it dosn't colide with the general css.

away around (for now) is to put every thing in a div with a style attribute with the style you need.

text=<div style="{{css}}"> {{ textcssed }} </div>
css=  lecssvpuluesuruneligne
textcssed==
the text you want 
==
some context elements must be checked with some details but this solution shloud work
