### ISSUE TITLE
TIme information

### ISSUE THREAD

**Issue by plgitlogin** [PremierLangage/premierlangage#144]
What elements if time information are stored in the data base ??

- each time an exercice is shown to a student ? how do i know this is the case ? 
- each time an exercice is tried by a student ? how do i know this is the case ? 

when a user see an exercice but goes away and then comme back in an other browser/machine/wathever the exercice is showed  again is there a way to know this is what happened ?

**Comment by Pavell94000** [comment]
>     * each time an exercice is shown to a student ? how do i know this is the case ?

An answer is stored in playexo_answer with a grade set to NULL.

>     * each time an exercice is tried by a student ? how do i know this is the case ?

An answer is stored in playexo_answer with a grade set to ]-inf, 100]

> when a user see an exercice but goes away and then comme back in an other browser/machine/wathever the exercice is showed again is there a way to know this is what happened ?

AFAIK, it is not possible.

**Comment by nimdanor** [comment]
Can the session know the IP of the browser and in case it changes the time between to reload is skiped ?
