### ISSUE TITLE
Integration of branch editor in project 0.5.0

### ISSUE THREAD

**Issue by plgitlogin** [PremierLangage/premierlangage#147]
@mclissee can you please update on github The branch fulleditor with the merge you did with master?
when done can you do a pull request on version 0.* (ask @qcoumes) on which one should be donne the pull request. 
Then we will be able to do the evaluation. 
@Pavell94000 can you check  the tests on the merge proposal, please.

**Comment by qcoumes** [comment]
The merge have to be done on 0.5.0

**Comment by nimdanor** [comment]
Happy to see this is going well.
