### ISSUE TITLE
Assets and Resources

### ISSUE THREAD

**Issue by nimdanor** [PremierLangage/premierlangage#149]
To return to # 46 without reopening it, we need to talk about the strategy of organizing the documents (resources) in the platform.
The platform is structured by to fundamental activities, **creating** didactic resources and **using** them with students. 
This is why we define TWO majors types/concepts: 
**Resources**: course elements, shared, reusable,  programmable, editable, what are stored in a unique global repository (like Wikipedia).  Every Resource pertaining to a given subject is stored in the same place. A classification system like Dewey is used to organize globally the themes. 
Resources are edited on the general server http://pl.u-pem.fr (for now). So in the old mechanism of file reference and access, the home directory is replaced by the course directory, i.e. the general directory wherein the classification the course is placed. For example, You want to teach Algebra then the directory is /mathematics/algebra/

**Assets**: class elements, specific, assigned to a class related to a resource. Assets are used in a class with students, an asset is linked to a resource (like an instance to its class in OOP). The code of the resource is used in the asset, but no modification of the resource is done in the class (except exceptional debug situations). Assets contain a finite set of information pertaining to the interaction of the asset with the student: (opening hours, access conditions, ..., teacher evaluations, etc). Those pieces of information are common to every asset, and, an HTML editor of these values is furnished.   

The impact of this on #46 is that the home dir must be replaced by the course dir. But as there is no evident course dir, the question must be asked to the teacher when he creates a new class to which directory in the general classification this new class is connected.

By default a new teacher with no course will be in the directory /conceptexo wich is a place to learn how to write exercises in the platform.

**Comment by qcoumes** [comment]
The idea for **ressources** seems good to me, but it is quite different from what we have now and will require a lot of work.

As for **assets**, i'm not sure I get what you meant. Are they supposed to modify the way a *ressource* work ?

And for when do you want all this ?

**Comment by nimdanor** [comment]
Assets are resources in use. 
The french "Actif" is better because it conveys the means that the resource is in use.
The resource is used in a classroom with students.

we allready have a lot off resources (exercises, and documents, Christophe is working on activities)
we allready have Assets (loaded Pl and loaded Pltp).
But we now have information associated with these loaded resources: assets  (active resources,  instances).

**Comment by nimdanor** [comment]
To answer your question Assets don't affect the way a resource works. 
It can only change information like, is it open for the students, is it optional, all kind of information not really related to the resource but to the use of the resource in the classroom.

**Comment by qcoumes** [comment]
Ok, so assets are like the state of a ressources according to a class.

What are the different files that we currently have in *lib* (templates, graders, builders, forms, ...) according to **ressources** and **assets**, where should we store them ?

**Comment by nimdanor** [comment]
The resource is supposed to be self-contained, when you pull a resource (pl, pltp) in the current version everything is put in the data base ?
It's why we don't have images no ?

So the same thing with an asset everything (of the resource)  is in the database except images (direct static elements of a resource : images, javascript code, html templates, etc). 
Direct elements are stored in a django datastore you spoked of ...(don't remember the name).

**Comment by qcoumes** [comment]
From what you said earlier, only the assets are self contained inside a PL/PLTP entry in the database once a .pl or a .pltp is loaded.

But what are graders, builders, ... ? Ressources, assets, something else ?

**Comment by qcoumes** [comment]
I guess PL/PLTP coulb be considered as ressources, and the assest more another table between them and the courses.

**Comment by nimdanor** [comment]
PL/PLTP/Documents/video/activities/etc are the resources they are shared between everyone and are editable. 
There is only one version of each resource on the official PL.u-pem.fr resource repository.
When you start a new classroom you do it on a classroom server, where you define the students and colleagues, and you import Resources that become Assets . By transforming them in Assets you add to them a group of properties: like open/close, evaluation function, that are specific to the classroom and not to the resource.
