### ISSUE TITLE
The label  doc  in a pl file 

### ISSUE THREAD

**Issue by nimdanor** [PremierLangage/premierlangage#152]
In template we ask the creators to write a label **doc** explaining how to use the template.

This is the right place to put this information. But we need a way to access it more easily than opening the template that contains code that can scare users. 
Is the editor able to show a popup containing the doc if we hover over a line containing **template** or **extends** ?

**Comment by mciissee** [comment]
This is not possible for now with the way the editor is implemented

**Comment by mciissee** [comment]
I think that this is not necessary because the user can click on the template/extends tag to open the resource in a new tab and read the content (why not with the doc tag inside it).

**Comment by nimdanor** [comment]
Yes the doc tag is inside the template.
But your idea is good.

**Comment by mciissee** [comment]
is this issue should be closed @nimdanor ?

**Comment by nimdanor** [comment]
Closed Now but will maybe reopen in the futur. It depend if we have a documentation for the plateform that is different from the documentation of the exercices ....
