### ISSUE TITLE
The @ operator 

### ISSUE THREAD

**Issue by plgitlogin** [PremierLangage/premierlangage#157]
We use the @ operator as the "file" operator this doesn't go very well with the decorator operator also @, we want to change the file operator to & or §.

This change should be done before the introduction of decorators. 

Question &. or § or another?

**Comment by nborie** [comment]
I do not even know how to type § on my qwerty keyboard... So I vote for &. 

Ok, google just told me that § is compose thus o thus s on linux qwerty... I still prefer &

**Comment by nthiery** [comment]
>    & should do the trick, but it's quite weird with its common meaning of
>    and.

It matches relatively reasonably with its other common meaning of
"reference" though:

        & /foo/bla.py bar.py

reference /foo/bla.py as bar.py in the sandbox. Although, it's in fact
a copy, not a reference ...

**Comment by nimdanor** [comment]
This syntax is the following in a pltp 

dic% {"seed":3, "a":"Dunkerck"}
@ plfilename % dic 
or directly 
@ aplfile %  {"seed":3, "a":"Dunkerck"}


see #366.
