### ISSUE TITLE
Enable direct push/pull access to PL's git repos

### ISSUE THREAD

**Issue by nthiery** [PremierLangage/premierlangage#16]
Example: currently, to push from a local repository to PL, one need to push to some remote repository,
and then pull from PL using it's git UI. Instead, one would want to directly push to PL, over either https or ssh.

Use case: as in #12: quicker remote edit & test loop

Bonus: enable ssh-key based authentication for password-less push.

**Comment by nimdanor** [comment]
Sure but no ideas how to do this. A git server ?

**Comment by nthiery** [comment]
>    Sure but no ideas how to do this. A git server ?

Yeah, I guess. With git+ssh, presumably not much of a server is
actually required; it should be sufficient to have an ssh server that
has access to the directories containing the local clones and
appropriate configuration to only allows running git commands. But I
haven't done it myself, so don't take my word!

**Comment by nimdanor** [comment]
Je ferme comme la physosohie (stratégie) et de partir sur  un repository (non-git) central qui gère "à la" wikipédia.
Il reste une partie des ressource qui reste sous git qui est la librairie standard.
