### ISSUE TITLE
The page template must be a parameter

### ISSUE THREAD

**Issue by plgitlogin** [PremierLangage/premierlangage#162]
It's not possible to remove the title or to change the layout of and exercice. That's bad.

The template should be parametrised by the exercice :
```html
jinja==
{% extends "classmanagement/base.html" %}
{% load static %}
{% block content %}
    <div class="row">
        <div class="col-md-1"></div>
        <div id="navigation" class="col-md-2">
            {{ navigation }}
        </div>
        <div id="exercise" class="col-md-8">
            {{ exercise }}
        </div>
        <div class="col-md-1"></div>
    </div>
{% endblock %}
==
```
or something like that.

**Comment by nimdanor** [comment]
where is the doc ?

**Comment by mciissee** [comment]
the doc of what?

**Comment by nborie** [comment]
Let me the time of destroy it entirely pls !

**Comment by nimdanor** [comment]
I am asking for the line of PL code i should use to change 
the jinja template that defines the <div id="exercice" > ....

**Comment by nimdanor** [comment]
@nborie i am not speeking of the global doc.

**Comment by mciissee** [comment]
The file **ESSAIS/mcisse/events.pl** on [](https://pl-preprod.u-pem.fr/filebrowser) shows an example of documented code.

**Comment by mciissee** [comment]
on https://pl-preprod.u-pem.fr/filebrowser

**Comment by nimdanor** [comment]
Thanks ;)

**Comment by nimdanor** [comment]
How did i miss that ? 
I don't know !
