### ISSUE TITLE
Transfert of plgitlogin/premierlangage to premierlangage

### ISSUE THREAD

**Issue by plgitlogin** [PremierLangage/premierlangage#164]
What will change if I transfert the onwership to organisation premierlangage ? 
what are the links we use directly inside http://github.com/plgitlogin/premierlangage/ ?

**Comment by qcoumes** [comment]
This should not impact PL in anyway.

The only problem I expect is for those having clone PL, every command interacting with origin (git pull, git push...) will not work anymore. They'd have to do:

`git remote set-url origin [new_url]`
