### ISSUE TITLE
Static file and images syntax

### ISSUE THREAD

**Issue by nimdanor** [PremierLangage/premierlangage#165]
We need a syntax for defining static files in pl i propose 
img != ./fileref
or
! /path/fileref [alias] 
and a syntax to put them in text 
text= le bo chat : {{img}} ou la belle andouille {{alias}}
May be we need more thant this because images have size positions etc -> creating a new issue.

**Comment by nthiery** [comment]
Just thinking out loud: the PL syntax is a bit looking like Perl, with
quite a few one-symbol operators having magic meanings. Could this be
improved by using names instead? Especially when a lot of the symbol's
meaning is not about the operation itself, but the "mime type" of the
content to be manipulated.

We could imagine instead having just the three natural operators "=,
==, +=", and one syntax for adding metadata, like e.g. is done for
code blocks in ResT. This would also leave the door for adding other
types of information later without having to change the syntax.

Maybe something like:

    foo = @json(...)

    foo == @json
    ...
    ==

I used @ because this is kind of a directive, but we could reserve
another symbol instead.

Variant:

    foo =[json] ...

    foo ==[type: json]
    ...
    ==

Cheers,

**Comment by nimdanor** [comment]
I agree we can have a open-ended syntax for types of variables in a pl file 
i propose 
variable={type}stringcastableinthetype

entier={int}12 
becomes
entier=int("""12""")
simple direct no hassle 
glop={mybioutifulclasse}{"field1":"value1,"filed2":"value2"}
becomes
glop=mybioutifulclase("""{"field1":"value1,"filed2":"value2"}""")
or is there a pythonic way with repr() ????

**Comment by qcoumes** [comment]
We can pass argument to a function with either a list, a dict or both.

For instance with a prototype like `func(a, b, c, d=None)`, you can:
```python
func(*[1, 2, 3, 4])
# Or
func(**{"a": 1, "b": 2, "c": 3, "d": 4})
# Or
func(*[1, 2], **{"c": 3, "d": 4})
# etc...
```
Obviously, any of these lists/dicts could be a variable, so `{Class}{"field1": "value1, "field2": "value2"}`
can  just be `Class(**{"field1": "value1, "field2": "value2"})`

The problem with something like `glop={Class}{"field1": "value1, "field2": "value2"}` is that the parser have no way to know the definition of the class.  Instantiation of classes is better done in the **builder**.

As for the built-in type, it could be very usefull to be able to give the type of a variable, for instance to avoid to have to use a **Builder** just to do some casts.

**Comment by nimdanor** [comment]
I agree with your two remarks 👍 

> The problem with something like glop={Class}{"field1": "value1, "field2": "value2"} is that the **parser** have no way to know the definition of the class. Instantiation of classes is better done in the builder.
> 
> As for the built-in type, it could be very useful to be able to give the type of a variable, for instance, to avoid to have to use a Builder just to do some casts.
> 

So let's say that this is good for built-in. I will create the  #169 issue for this.

# Now for the syntax for static files

What are static files?
They are file usable directly in the HTML of exercises, activity, dashboard etc.
So we can use them in jinja_templates, Django/templates/ in HTML constructs like 
<img src="The static file reference">
<script src="The static file.js reference">
<a href="the static file reference"> Oh le bo document </a>

So we must construct a full address made:
 with the server (or a file server)
with a local reference in the server 

One problem we must solve is that we don't want to copy multiple time a file especially huge files like images and video.

So the reference in the resource (the pl, the activity, ... ) must be linked to the internal reference and must be translated to a local reference and the file transmitted when the resource is transformed in an asset.

**Comment by mciissee** [comment]
See #264
