### ISSUE TITLE
No color in navigation

### ISSUE THREAD

**Issue by Pavell94000** [PremierLangage/premierlangage#167]
When you do an exercise (successfully or not), the navigation stays gray.
The bug exists on both pl prod and branch full_editor.

**Comment by Pavell94000** [comment]
Fixed in full_editor

**Comment by nimdanor** [comment]
Is there a test to check this in the futur ??

**Comment by qcoumes** [comment]
As far as I know there's no way to check whether a CSS class is found or not.

**Comment by nimdanor** [comment]
Can't you check if a text is green ??
