### ISSUE TITLE
Accès à pl-test4

### ISSUE THREAD

**Issue by nimdanor** [PremierLangage/premierlangage#170]
Je n'arrive pas (sans créer une activité) a me connecter sur pl-test4 à partir de elearning. 
C'est normal ?

**Comment by qcoumes** [comment]
I don't know, I'll check this tomorrow's afternoon if I have enough time.

**Comment by nimdanor** [comment]
Maintenant j'ai un vrais problème sur pl-test4:
Jan 25 11:52:17.746448 2019] [wsgi:error] [pid 15928] [remote 193.50.159.53:57185] mod_wsgi (pid=15928): Target WSGI script '/srv/local/pl/premierlangage4/server/serverpl/serverpl/wsgi.py' cannot be loaded as Python module.
[Fri Jan 25 11:52:17.746526 2019] [wsgi:error] [pid 15928] [remote 193.50.159.53:57185] mod_wsgi (pid=15928): Exception occurred processing WSGI script '/srv/local/pl/premierlangage4/server/serverpl/serverpl/wsgi.py'.
[Fri Jan 25 11:52:17.747804 2019] [wsgi:error] [pid 15928] [remote 193.50.159.53:57185] Traceback (most recent call last):
[Fri Jan 25 11:52:17.747866 2019] [wsgi:error] [pid 15928] [remote 193.50.159.53:57185]   File "/srv/local/pl/premierlangage4/server/serverpl/serverpl/wsgi.py", line 23, in <module>
[Fri Jan 25 11:52:17.747875 2019] [wsgi:error] [pid 15928] [remote 193.50.159.53:57185]     application = get_wsgi_application()
[Fri Jan 25 11:52:17.747886 2019] [wsgi:error] [pid 15928] [remote 193.50.159.53:57185]   File "/srv/local/pl/premierlangage4/env/lib/python3.5/site-packages/django/core/wsgi.py", line 12, in get_wsgi_application
[Fri Jan 25 11:52:17.747893 2019] [wsgi:error] [pid 15928] [remote 193.50.159.53:57185]     django.setup(set_prefix=False)
[Fri Jan 25 11:52:17.747903 2019] [wsgi:error] [pid 15928] [remote 193.50.159.53:57185]   File "/srv/local/pl/premierlangage4/env/lib/python3.5/site-packages/django/__init__.py", line 24, in setup
[Fri Jan 25 11:52:17.747910 2019] [wsgi:error] [pid 15928] [remote 193.50.159.53:57185]     apps.populate(settings.INSTALLED_APPS)
[Fri Jan 25 11:52:17.747920 2019] [wsgi:error] [pid 15928] [remote 193.50.159.53:57185]   File "/srv/local/pl/premierlangage4/env/lib/python3.5/site-packages/django/apps/registry.py", line 112, in populate
[Fri Jan 25 11:52:17.747926 2019] [wsgi:error] [pid 15928] [remote 193.50.159.53:57185]     app_config.import_models()
[Fri Jan 25 11:52:17.747937 2019] [wsgi:error] [pid 15928] [remote 193.50.159.53:57185]   File "/srv/local/pl/premierlangage4/env/lib/python3.5/site-packages/django/apps/config.py", line 198, in import_models
[Fri Jan 25 11:52:17.747943 2019] [wsgi:error] [pid 15928] [remote 193.50.159.53:57185]     self.models_module = import_module(models_module_name)
[Fri Jan 25 11:52:17.747954 2019] [wsgi:error] [pid 15928] [remote 193.50.159.53:57185]   File "/usr/lib/python3.5/importlib/__init__.py", line 126, in import_module
[Fri Jan 25 11:52:17.747960 2019] [wsgi:error] [pid 15928] [remote 193.50.159.53:57185]     return _bootstrap._gcd_import(name[level:], package, level)
[Fri Jan 25 11:52:17.747971 2019] [wsgi:error] [pid 15928] [remote 193.50.159.53:57185]   File "<frozen importlib._bootstrap>", line 986, in _gcd_import
[Fri Jan 25 11:52:17.747982 2019] [wsgi:error] [pid 15928] [remote 193.50.159.53:57185]   File "<frozen importlib._bootstrap>", line 969, in _find_and_load
[Fri Jan 25 11:52:17.747992 2019] [wsgi:error] [pid 15928] [remote 193.50.159.53:57185]   File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
[Fri Jan 25 11:52:17.748003 2019] [wsgi:error] [pid 15928] [remote 193.50.159.53:57185]   File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
[Fri Jan 25 11:52:17.748013 2019] [wsgi:error] [pid 15928] [remote 193.50.159.53:57185]   File "<frozen importlib._bootstrap_external>", line 673, in exec_module
[Fri Jan 25 11:52:17.748024 2019] [wsgi:error] [pid 15928] [remote 193.50.159.53:57185]   File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
[Fri Jan 25 11:52:17.748034 2019] [wsgi:error] [pid 15928] [remote 193.50.159.53:57185]   File "/srv/local/pl/premierlangage4/server/serverpl/playexo/models.py", line 18, in <module>
[Fri Jan 25 11:52:17.748040 2019] [wsgi:error] [pid 15928] [remote 193.50.159.53:57185]     from classmanagement.models import Course
[Fri Jan 25 11:52:17.748050 2019] [wsgi:error] [pid 15928] [remote 193.50.159.53:57185]   File "/srv/local/pl/premierlangage4/server/serverpl/classmanagement/models.py", line 6, in <module>
[Fri Jan 25 11:52:17.748068 2019] [wsgi:error] [pid 15928] [remote 193.50.159.53:57185]     from lti.models import LTIModel
[Fri Jan 25 11:52:17.748095 2019] [wsgi:error] [pid 15928] [remote 193.50.159.53:57185] ImportError: No module named 'lti.models'
[Fri Jan 25 11:52:17.952290 2019] [wsgi:error] [pid 15928] [remote 193.50.159.53:57184] mod_wsgi (pid=15928): Target WSGI script '/srv/local/pl/premierlangage4/server/serverpl/serverpl/wsgi.py' cannot be loaded as Python module.
[Fri Jan 25 11:52:17.952334 2019] [wsgi:error] [pid 15928] [remote 193.50.159.53:57184] mod_wsgi (pid=15928): Exception occurred processing WSGI script '/srv/local/pl/premierlangage4/server/serverpl/serverpl/wsgi.py'.
[Fri Jan 25 11:52:17.952451 2019] [wsgi:error] [pid 15928] [remote 193.50.159.53:57184] Traceback (most recent call last):
[Fri Jan 25 11:52:17.952529 2019] [wsgi:error] [pid 15928] [remote 193.50.159.53:57184]   File "/srv/local/pl/premierlangage4/server/serverpl/serverpl/wsgi.py", line 23, in <module>
[Fri Jan 25 11:52:17.952540 2019] [wsgi:error] [pid 15928] [remote 193.50.159.53:57184]     application = get_wsgi_application()
[Fri Jan 25 11:52:17.952553 2019] [wsgi:error] [pid 15928] [remote 193.50.159.53:57184]   File "/srv/local/pl/premierlangage4/env/lib/python3.5/site-packages/django/core/wsgi.py", line 12, in get_wsgi_application
[Fri Jan 25 11:52:17.952561 2019] [wsgi:error] [pid 15928] [remote 193.50.159.53:57184]     django.setup(set_prefix=False)
[Fri Jan 25 11:52:17.952572 2019] [wsgi:error] [pid 15928] [remote 193.50.159.53:57184]   File "/srv/local/pl/premierlangage4/env/lib/python3.5/site-packages/django/__init__.py", line 24, in setup
[Fri Jan 25 11:52:17.952579 2019] [wsgi:error] [pid 15928] [remote 193.50.159.53:57184]     apps.populate(settings.INSTALLED_APPS)
[Fri Jan 25 11:52:17.952590 2019] [wsgi:error] [pid 15928] [remote 193.50.159.53:57184]   File "/srv/local/pl/premierlangage4/env/lib/python3.5/site-packages/django/apps/registry.py", line 81, in populate
[Fri Jan 25 11:52:17.952598 2019] [wsgi:error] [pid 15928] [remote 193.50.159.53:57184]     raise RuntimeError("populate() isn't reentrant")
[Fri Jan 25 11:52:17.952635 2019] [wsgi:error] [pid 15928] [remote 193.50.159.53:57184] RuntimeError: populate() isn't reentrant
root@pl-test:/var/log/apache2#

**Comment by qcoumes** [comment]
La seconde erreur provient d'un conflit entre [un module externe lti](https://pypi.org/project/lti/) que j'avais installer pour wimsLTI et l'app du même nom dans PL. Il faut voir pour renommer l'app en question en quelque chose différent que *lti*, `lti_app` par exemple.

J'ai désinstaller le module lti en attendant.

Pas eu le temps de regarder pour la première erreur.

**Comment by nimdanor** [comment]
old stuff i close, every thing as changed since closing.
