### ISSUE TITLE
Accès refuser (403)

### ISSUE THREAD

**Issue by nimdanor** [PremierLangage/premierlangage#173]
Accès refuser (403)

**Comment by nimdanor** [comment]
Accès Revuzé

**Comment by nimdanor** [comment]
C pas moi !

**Comment by nborie** [comment]
Ach... Fou Zavé eu L'akzé Revuzé ! Fou Zavet Pas Tappèz Lé Gut Mot Dé Paz !

**Comment by qcoumes** [comment]
Y a vraiment un problème ?

**Comment by nborie** [comment]
Moi, j'ai compris ça : "Pourriez-vous coder s'il vous plait une page d'erreur portant le numéro 403 signifiant à l'utilisateur que la connexion lui est refusée ?"

Bon après, j'ai peut-être mal compris... Le patron à dit "Accès refuser (403)". Après comme le montre mon avatar, certains descendent du singe plus vite que les autres....

**Comment by qcoumes** [comment]
Si c'est ça, ce talent d'interprétation est remarquable.

En revanche, [cette page existe déjà](https://github.com/PremierLangage/premierlangage/blob/master/server/serverpl/templates/403.html).

**Comment by nborie** [comment]
Je vais retourner consulter grand chaman et petit volcan... Peut-être les vents favorables rapporteront de meilleures interprêtations de la sagesse du patron ?

Nous ne sommes pas prêt...

**Comment by nimdanor** [comment]
ACCÈS REFUSÉ (403)
Pour une fois que je fais une remarque d'orthographe ;)

**Comment by nimdanor** [comment]
Enfin de compte la faute d'orthographe est toujours la ...
Donc je ré-ouvre ....

**Comment by qcoumes** [comment]
Corrigé depuis 0aa4c23b73c710ba664eae850bef1503a8818069, qui est sur master.
