### ISSUE TITLE
Cannot use apply option git_push: Path must point to a directory

### ISSUE THREAD

**Issue by nimdanor** [PremierLangage/premierlangage#174]
Bof
y a qu'a prendre le répertoire contenant le fichier sélectionné. Comme cela y a pas d'erreur.
Et cela revient au même pour l"utilisateur.

I get this when using git push while a plain file is selected in the filebrowser.

**Comment by qcoumes** [comment]
AFAIK, *gitcmd*'s push should work with a path leading to a file.

**Comment by mciissee** [comment]
git push works with files and directories I don't know how you had this bug
