### ISSUE TITLE
Renaming with out ESC make strange view

### ISSUE THREAD

**Issue by nimdanor** [PremierLangage/premierlangage#176]
As you see :
<img width="1518" alt="capture d ecran 2019-01-30 20 42 57" src="https://user-images.githubusercontent.com/10084549/52007855-b1b88180-24cf-11e9-8eb2-cf31b672b3c1.png">
and when i <return> in the textfield I got the error message

**Comment by mciissee** [comment]
I cannot reproduce this bug, how did you get this one ?

**Comment by nimdanor** [comment]
﻿﻿click on rename 
click elsewere on rename 
click on another directory 
you have 2 renamed open 
you should close the rename texteedit when you click on something else when it loose the focus.

**Comment by mciissee** [comment]
fixed !
