### ISSUE TITLE
Les tests sont insuffisants :

### ISSUE THREAD

**Issue by plgitlogin** [PremierLangage/premierlangage#177]
Une erreur s'est produit sur la sandbox (exit code: -1, env: ad000d26-ad63-4e59-9b44-243a41c2abac). Merci de prévenir votre professeur.

An unknown error occured:
Traceback (most recent call last):
  File "/srv/local/pl/pl-sandbox/sandbox/views.py", line 112, in post
    container = ContainerWrapper.acquire()
  File "/srv/local/pl/pl-sandbox/sandbox/container.py", line 71, in acquire
    cw = next((c for c in settings.CONTAINERS if c.available), None)
  File "/usr/local/lib/python3.5/dist-packages/django/conf/__init__.py", line 58, in __getattr__
    val = getattr(self._wrapped, name)
AttributeError: 'Settings' object has no attribute 'CONTAINERS'

**Comment by nimdanor** [comment]
la prod pl.u-pem.fr

**Comment by nimdanor** [comment]
Quand je dit que les tests sont insuffisants
ils ne vérifient pas un cycle d'utilisation complet.
Il faut peut être ajoute un type de test qui utilise un navigateur pour vérifier le fonctionnement.
https://wiki.saucelabs.com/display/DOCS/Getting+Started+with+Selenium+for+Automated+Website+Testing

**Comment by nimdanor** [comment]
Mieux
https://pypi.org/project/selenium/

**Comment by qcoumes** [comment]
C'est surtout qu'il n'y a pas de tests sur la sandbox.

On a déjà rencontré se bug avec @Pavell94000, il avait restart docker il me semble.

**Comment by Pavell94000** [comment]
En effet on avait déjà eu le problème et impossible de trouver la source. J'avais complètement réinstallé la sandbox. Après on l'a déjà réinstallé hier matin, du coup ???

**Comment by nimdanor** [comment]
Oui mais un test selenium devrait détecter le problème.
d'autre part sur preprod l'editeur n'affichage pas le contenu des fichier 
par contre playexo sur ces fichiers fonctionne ...

**Comment by Pavell94000** [comment]
Je n'ai pas de problème pour afficher les fichier sur preprod, ça vient peut etre du navigateur ? Je crois que Mamadou est en train de régler les problèmes de navigateur.
Je vais voir pour mettre en place selenium sur preprod

**Comment by nimdanor** [comment]
j'ai une présentation demain à 14h je l'annule ??
@qcoumes @Pavell94000 

 Une erreur s'est produit sur la sandbox (exit code: -1, env: 380bf806-4be0-439b-b3f0-26c191ce3422). Merci de prévenir votre professeur.



An unknown error occured:
Traceback (most recent call last):
  File "/srv/local/pl/pl-sandbox/sandbox/views.py", line 112, in post
    container = ContainerWrapper.acquire()
  File "/srv/local/pl/pl-sandbox/sandbox/container.py", line 102, in acquire
    cw = next((c for c in CONTAINERS if c.available), None)
TypeError: 'NoneType' object is not iterable

**Comment by nimdanor** [comment]
ni pl ni pl-preprod
c'est possible d'avoir une vieille sandbox .... qui marche ??
plusieurs .... ?? 
c'est con de pas pouvoir avoir plusieurs sandbox ...

**Comment by nimdanor** [comment]
NRV

**Comment by qcoumes** [comment]
D'où l'importance de faire des tests et d'effectuer correctement les codes review.

Le mieux à faire pour votre réunion, c'est de repasser la sandbox de pl-preprod à la dernière version stable.

Après, comme il n'y a de plus aucun versionage sur la sandbox, faut chercher le commit du merge du pull request à la main.

Je ferais ça demain entre 8h30 et 10h.

**Comment by qcoumes** [comment]
En ce  qui concerne le problème en lui même, il semble que apache éteins les serveur après un temps d'inactivité, il faut regarder les logs et la doc.

Si c'est le cas, il faut récupéré les containers existants au lieu de les réinitialiser.

**Comment by Pavell94000** [comment]
Une autre solution temporaire pourrait-être de mettre un script qui redémarre docker et apache2 tout les matins, en attendant de trouver un moyen de changer la config apache

**Comment by Pavell94000** [comment]
Vu que le  probleme ne semble pas venir de la  sandbox, mais d'apache qui stoppe les containers, ca serait  dommage d'annuler l'amélioration de vitesse non ?

**Comment by qcoumes** [comment]
Quand je parlais de repasser à la dernière version stable, c'était de manière temporaire, le temps de voir d'où vient le problème, et comment le régler.

**Comment by qcoumes** [comment]
@nimdanor J'ai remis l'ancienne sandbox sur pl-preprod, elle fonnctionne donc mais est beaucoup plus lente.

**Comment by nimdanor** [comment]
Pour les tests, nous devons noter tous les probèmes que l'on a eux avec cette version pour qu'un test nous permette de le détecter la prochaine fois..
je sais c'est une porte déjà ouverte mais ...


donc Il faut:
Un test d'un exercice complet dans un pltp avec sellenium, qui verifie les feedbacks et une evaluation raté grade=0 et réussi grade=100. 
Que le feedback est bein affiché correctement dans les deux cas.
Et que ce feedback contient du latex qui est correctement affiché.

**Comment by nimdanor** [comment]
@Pavell94000 tu peux faire un point de ce que tu a vu ce matin avec Nicolas Cuvelier

**Comment by Pavell94000** [comment]
J'ai commencer a écrire des tests avec Splinter (surcouche de Selenium) pour l'utilisation du filebrowser, des exercices etc...

Pour ce matin, on a tenté de trouver l'origine de la suppression des containers sans arriver à reproduire le bug. 
Le seul truc qui se passe sur les serveur est un reload d'apache vers 6h30 du matin, mais lorsqu'on faisait un reload manuel, les containers se relançaient correctement apres une requete.
Du coup on a rajouté un curl qui se fait sur la sandbox toutes les heures pour relancer les containers si apache a restart / reload.
Si cela ne suffit pas, j'y retournerai demain matin

**Comment by qcoumes** [comment]
Je viens de faire [une nouvelle version](https://github.com/plgitlogin/sandbox/pull/23) de la sandbox, donc si les changements que vous avez fait passent pas, faudrait voir si ceux de la nouvelle version passe la nuit sur preprod, donc plutôt aller au CRI à partir de mercredi.

**Comment by Pavell94000** [comment]
La sandbox semble avoir passer la nuit sur la prod et sur les pl-test...

**Comment by nimdanor** [comment]
La version 0.5.3 est donc sécurisé, est elle notre première candidate pour une release ?
