### ISSUE TITLE
Ctrl+S sur l'éditeur étudiant

### ISSUE THREAD

**Issue by laurent-bulteau** [PremierLangage/premierlangage#181]
Faire en sorte que ctrl+s déclenche une sauvegarde y compris pour l'éditeur de code étudiant

**Comment by mciissee** [comment]
La commande Ctrl+S déclenche normalement une sauvegarde (Cmd+S sur macOS)

**Comment by qcoumes** [comment]
@mciissee Sur l'éditeur étudiant aussi ?

**Comment by mciissee** [comment]
@qcoumes non uniquement sur l'éditeur des professeurs.
Qu'est ce qu'il est possible de sauvegarder sur l'éditeur étudiant ?

**Comment by laurent-bulteau** [comment]
Il y a un bouton "sauvegarder" en bas de la zone pour coder : et en général on peut s'attendre à ce qu'un étudiant qui fasse "ctrl+s" en tapant du code n'ait pas envie de sauver la page html

**Comment by mciissee** [comment]
Effectivement la commande ctrl+s sauvegarde la page html. Ce problème sera corrigé dans la prochaine release.

**Comment by nimdanor** [comment]
Il faut que l'éditeur de code etudiant soit uptodate vous savez comme moi comme ils sont exigeants ;)

**Comment by nimdanor** [comment]
@mciissee il faut un rafraichissement général du look des exercices. 
Et donc que l'on puisse modifier le template/jinja + css utilisé dans l'exercice.
un look and feel wims pour les exercices serai un bonus sympa ;)

**Comment by mciissee** [comment]
L'utilisation du composant CodeEditor règle ce problème.
