### ISSUE TITLE
Le grader de divisible par 7 marche pas !

### ISSUE THREAD

**Issue by forax** [PremierLangage/premierlangage#182]
Une erreur s'est produite lors de l'exécution du grader (exit code: 1, env: 40ccae71-a5bd-4c5f-a3f3-7ad6e9d8196d_built). Merci de prévenir votre professeur
Received on stderr:

Traceback (most recent call last):
  File "grader.py", line 44, in 
    dico_tests = eval( dic['tests'] )
  File "", line 12

^

SyntaxError: unexpected EOF while parsing

**Comment by nimdanor** [comment]
We should have a email system to send to the author in that case if we are in production.

**Comment by nimdanor** [comment]
this should no be in this repo but in project conceptexo
this issue should be written more clearly with a référence to the exercice.

**Comment by plgitlogin** [comment]
@forax you have to change the 'tests' key in your exercice.
