### ISSUE TITLE
Renomer la fonction pieds_sort en pied donne une erreur bizarre

### ISSUE THREAD

**Issue by forax** [PremierLangage/premierlangage#183]
Si au lieu de pieds_sort on écrit juste pied, le message d'erreur est pas super clair.

basic.c: In function ‘main’:
basic.c:25:3: warning: implicit declaration of function ‘pieds_sort’ [-Wimplicit-function-declaration]
pieds_sort(tab, 0, nb_term-1);
^~~~~~~~~~
/tmp/ccV7y54o.o: In function `main':
basic.c:(.text+0x12c): undefined reference to `pieds_sort'
collect2: error: ld returned 1 exit status

**Comment by nimdanor** [comment]
This is a conceptexo issue.
