### ISSUE TITLE
Drag&Drop dans l'arbre du filebrowser

### ISSUE THREAD

**Issue by forax** [PremierLangage/premierlangage#185]
Si on fait un Dnd dans l'arbre du filebrowser, d'un fichier d'un répertoire vers un autre.
On a un message nous indiquant que l'on sort de la page (ce qui est bizzare),
si on dit ok pour sortir de la page on va sur un site web bizarre.

**Comment by mciissee** [comment]
Si le message est un message du navigateur indiquant que la page doit être fermé c’est que vous avez du faire un swipe back sans faire exprès lors du drop sinon c’est effectivement un bug

**Comment by forax** [comment]
Non, Dominque lors de la demo a eu le même message d'erreur.

**Comment by mciissee** [comment]
Ok merci d’avoir fais remonter le bug

**Comment by mciissee** [comment]
C'était finalement un problème de compatibilité avec certains navigateurs comme les anciennes versions de firefox qui détectent un évènement onbeforeunload lors d'un dnd .
