### ISSUE TITLE
problème d'accents

### ISSUE THREAD

**Issue by nimdanor** [PremierLangage/premierlangage#187]
IL semble que les lettre accentué écrites en deux temps ne fonctionne pas.
apparaissent en double

**Comment by mciissee** [comment]
Un screen du bug serait peut être utiles

**Comment by niotie** [comment]
Voilà une capture. J’ai appuyé sur la touche « accent aigu » (Shift-Alt-1 sous Mac) puis i majuscule, et deux caractères sont ajoutés à l'éditeur.
<img width="752" alt="capture d ecran 2019-02-08 a 10 40 56" src="https://user-images.githubusercontent.com/12487671/52470454-7a606980-2b8e-11e9-9d49-5e2bcf7229d8.png">
