### ISSUE TITLE
network breakout

### ISSUE THREAD

**Issue by igel-kun** [PremierLangage/premierlangage#188]
using the exercise editor, it seems possible to connect to the internet (also, the user running the exercises seems to be root)
![shot-2019-02-07_16-27-40](https://user-images.githubusercontent.com/1258108/52422260-03779200-2af6-11e9-8302-537a9e1c3662.jpg)

**Comment by qcoumes** [comment]
This is intended, exercises are run inside a Docker container as root, these container do have internet access as it allow more kind of exercises (using online ressouces, webcrawling...) and as far as we know, it does not cause any security issue.

**Comment by nimdanor** [comment]
that's arguable.
The "right" way is to set a proxy in the server for the sandbox in the case we want to let the students access the net.

Net access should be closed in next revision, and let's wait for the need to arise to implement a proxy.

**Comment by nimdanor** [comment]
This issue is now transfered to Network exercices on the sandbox 
https://github.com/plgitlogin/sandbox/issues/28
