### ISSUE TITLE
CMD-W

### ISSUE THREAD

**Issue by nimdanor** [PremierLangage/premierlangage#191]
In filebrowser/editor mode
Ctrl-w close the current editor window if the file was not modified.

**Comment by mciissee** [comment]
The command Ctrl-W will close the focused tab and Ctrl-Alt-W will close all opened tabs after a confirmation of the user. As Cmd-W command is used by some browsers like chrome I have chosen Ctrl instead of Cmd this is the same for save command Ctrl-S instead of Cmd-S
