### ISSUE TITLE
Problems with the mathjax filter

### ISSUE THREAD

**Issue by nimdanor** [PremierLangage/premierlangage#198]
It seams that the mathjax filter is not applied to the text after the grading step.
<img width="658" alt="capture d ecran 2019-02-11 a 21 57 25" src="https://user-images.githubusercontent.com/10084549/52593058-4f08a380-2e48-11e9-8ac6-1ab48cd774f5.png">

**Comment by nimdanor** [comment]
The problem of having the filters applyed when there is just an ajax call is solved ?

**Comment by qcoumes** [comment]
@mciissee I don't know about your branch, but on pl-preprod (master) it is not fixed

**Comment by esandier** [comment]
it is possible to render mathjax content in a div by the following javascript code
~~~~
MathJax.Hub.Queue(["Typeset",MathJax.Hub,feedback_div]);
~~~~
