### ISSUE TITLE
problem with the open button

### ISSUE THREAD

**Issue by nimdanor** [PremierLangage/premierlangage#201]
On pl.u-pem.fr
with the file python-pl-bank/template/pltest.pl open when i click on the open button 
for the file 
@ evaluator.py 
it's the file from osbank/template/parametrized_MCQ_evaluator.py that opens 
Strange (the getlocation is doing a trick here ?)

**Comment by mciissee** [comment]
This issue is already fixed on the editor_upgrade branch with a server call to get_location function

**Comment by nimdanor** [comment]
good.

**Comment by mciissee** [comment]
No it will be in the 0.5.3 release
