### ISSUE TITLE
External Java Script files not loading

### ISSUE THREAD

**Issue by ddoyen** [PremierLangage/premierlangage#202]
In some PL exercises, I use external Java Script files with cdn links (in the key `form`).

For example, I use the MathLive scripts to include a Latex-formatted mathematical input field.

~~~~
<script src="https://cdn.jsdelivr.net/npm/mathlive@0.26.0/dist/mathlive.js"></script>
<script src="https://cdn.jsdelivr.net/npm/mathlive@0.26.0/dist/mathlive.mjs"></script>
~~~~

In some configurations, the scripts seem not to be loaded.

1. When I launch the PL exercise in the "preview mode" in the editor (while it works in the "test mode" or when it is included in a pltp sheet).
2. After the student validates an answer and the exercise is reloaded.

**Comment by qcoumes** [comment]
May be link to #198
