### ISSUE TITLE
Changement du mode de gestion de Yggdrasil

### ISSUE THREAD

**Issue by nimdanor** [PremierLangage/premierlangage#204]
L'idée est qu'il faut passer l'arborescence des ressources sur un git unique et "caché" aux utilisateurs.
C'est une première étape vers un partage plus intelligent qui lui est discuté dans https://github.com/PremierLangage/plconception/blob/master/conception/concept/partage.md.

Pour cette issue le cahier des charges est le suivant : 
- un git qui gère tout ce qui est dans le répertoire yggdrasil dans un repository git  local (avec une sauvegarde dans un git de sauvegarde externe/privé toutes les nuits).  
- toute sauvegarde d'un fichier créer une version 
- il faut une interface permettant de créer un tag pour une "photographie/version au sens git" qui est utilisable par le module activité (to be specified)
- il faut une interface de visualisation des versions et des diff et la possibilité de replacer une version comme étant la dernière (downgrade).
- il faut préalablement définir une liste de répertoires structurant yggdrasil. @magdalena-kobylanski

**Comment by nborie** [comment]
J'ai commencé à en écrire de ce coté :

https://github.com/PremierLangage/plconception/blob/master/PROJETS/git_inside.md

**Comment by magdalena-kobylanski** [comment]
J'ai plusieurs questions concernant la gestion des modifications d'une "graine de connaissance de type exercice.pl" Ces questions concernent  des modifications d'un fichier pour 

(a) les fautes d'orthographes, 
(b) le débuggage, 
(c)  le versionning. 

 Comment gère-t-on ces modifications nécessaires ? fait-on simplement confiance ? 
Vient aussi la question de

(d)  l'hérédité. 

Comment des corrections d'un ancêtre vont-elles être transférées à ses descendants ? Faut-il un traitement différent suivant que l'on est dans (a), (b) ou (c) ? 

Faut-il que le système indique que lorsqu'un exercice est hérité un nombre n de fois (n à préciser), on incite à changer l'exercice en question en élément d'une librairie ?  

Concernant le versionning faut il une norme éditoriale ? Par exemple 
- un tag spécifique pour les exercices rédigés à l'infinitif, sur un ton neutre... 
- un autre tag pour les exercices rédigés a la deuxième personne du singulier, sur un ton plus proche. 
- un style csv par défaut très neutre. Avec un tag si on respecte ce style ou pas ?

**Comment by magdalena-kobylanski** [comment]
Comment fait-on dans WIMS ? 

 Les auteurs sont formés à la publication lors de leur premier dépôt. Après on leur fait confiance en général. 

Il existe deux endroits d'où un exercice est stocké et d'où il peut être exécuté : 
- la classe, et dans ce cas le prof peut faire des modifications dessus en directe, corriger des erreurs, debuggage. En règle général c'est très utile, car on a vite fait de prendre un paramètre trop général.
- le dépôt général. Là seul l'auteur peut faire des motifs et elles sont mises à jour toutes les nuits. 

En pratique les exercices sont testés un certain temps dans des classes et débuggués en directe au cours des premières utilisations. Elles sont ensuite publiées si le prof est adoubé. Sinon elles ne sont jamais publiées.

**Comment by nimdanor** [comment]
Premièrement : le cadre de cette issue est de définir une approche simplifiée du partage.
Approche que nous appellerons git_inside voir le document de Nicolas pour l'approche technique:  [git inside](https://github.com/PremierLangage/plconception/blob/master/PROJETS/git_inside.md)

**Les objectifs de ce partage est de ne pas avoir de conflits d’éditions irrémédiables entre auteurs.**
Mais pas de d'avoir de l'**editorialisation** qui elle doit être définie dans le document :  [Partage](https://github.com/PremierLangage/plconception/blob/master/conception/concept/partage.md)

Donc conservation de "toutes" les versions de fichier (chaque sauvegarde) et un outil pour visiter l'historique et la possibilité de

**Comment by nborie** [comment]
Je me suis un peu énervé sur 

https://github.com/PremierLangage/plconception/blob/master/PROJETS/git_inside.md

En réfléchissant aux use-cases, je continue à penser que la tâche ne sera pas facile et que l'on peut très très facilement faire des choix désastreux. Le temps passé sur ce document ne sera pas perdu 
* Ce sera une base pour la documentation (et il en faudra pour les enseignants-éditeurs)
* Les jeunes ne vont pas coder une roue carrée si on leur propose une stratégie raisonnable et bien décrite
* Il y a des questions profondes de design à arbitrer...

La puissance de git sans les contraintes techniques, c'est un rêve fou (sinon git l'aurait fait avant nous...). Je ré-itère les warnings en disant : il faut vraiment penser en parallèle fonctionnel et technique pour faire les bonnes délibération entre robustesse, simplicité, efficacité et performance... On ne pourra clairement pas tout avoir.

**Comment by magdalena-kobylanski** [comment]
C'est drôlement chouette quand tu t'énerves un peu ! 

100% d'accord : nous ne pourrons pas tout avoir. 
Question : que privilégier ? 

Ma réponse : la qualité des ressources. 

Vu les contorsions que les uns et les autres étaient capables de faire pour rentrer dans WIMS, par ce qu'il y a des ressources de qualité je parie sur le fait de privilégier avant tout ces ressources. 

Le fait d'autoriser tout le monde à créer des ressources est un plus qui doit se mériter par un petit effort ;-)

Qu'en pensez-vous ?

**Comment by nimdanor** [comment]
Je suis pour la qualité des ressources, Et donc la qualification des ressources et donc des labels:

je suis pour des labels définis par des cercles d'utilisateurs
je suis pour des exercices copiés/collés si il y a deux cercle qui sont pas d'accord
je suis pour des labels de types différents 👍 
- label langage / niveau de langage / linguistique
- label niveau scolaire 
- label qualité 
- label valeur pédagogique 
- label "exercice de chute" 
- label de bloom 
- label introductif/
Pour ces labels je propose une structure de méta-data externes aux exercices pour éviter de générer des versions.


D'autre part au niveau technique je comprend l'inquiétude de Nicolas.  
Mais si git le fait pas Wikipédia le fait, sur https://fr.wikipedia.org/wiki/Yggdrasil  si tu regarde l'[historique](https://fr.wikipedia.org/w/index.php?title=Yggdrasil&dir=prev&action=history)
tu vois qu'il y a toutes les versions et cela remonte à 2013. 

Mais En effet Il faut scénariser les opérations possible. A cet effet je fait mes commentaires dans git_inside.

**Comment by nimdanor** [comment]
Un premier point pour rebondir sur ton document nicolas c'est 👍 

d'un point de vue technique   unfichier==une ressource versionné par git 
d'un point de vue fonctionnel une ressource => un ensemble de fichiers cohérents 

le souci est dans le "cohérent".

je pense que le moment de publication est important car il valide un ensemble cohérent.
La publication est le passage d'une ressource à un actif (resource to asset)  

je pense aussi qu'un utilisateur a besoin de se protéger contre des modifications intempestives en marquant un ensemble de document. Pour faire ce marquage il faut appliquer le même algorithme de parcours que pour la publication (sans réaliser la création de l'asset).

Comment rendre un ensemble de fichiers "cohérent" il faut une configuration 
Une configuration connait pour chaque document la version qui correspond à la configuration.

Le truc c'est que les exercices sont pas publiables directement et donc il faut une autre forme de validation/publication spécifique. Je pense à un système de tests. 
Il faut qu'un exercice (ou un type) soit fournis avec un test unitaire et un test fonctionnel. 
Le test s'hérite avec le template, si le nouvel exercice case le test il faut peut être créer un nouveau template?
