### ISSUE TITLE
accès aux activités

### ISSUE THREAD

**Issue by nimdanor** [PremierLangage/premierlangage#207]
Les étudiants de INFO2 ce matin m'on fait remarquer que si je change le numéro d'activité dans l'URL j'ai accès a des activités auxquelles je ne devrai pas accéder (PLTP de C++ par exemple ).

Il n'y a donc pas de vérification que l'activité courante est liée à un cours auquel on a accès.

**Comment by nborie** [comment]
Je ne vais pas dire Duplicate mais Hugo (de Paris-Sud) a effectivement levé cette faille pour la disponibilité prématurée des épreuves d'examen.... Le risque est réel en effet....

**Comment by nborie** [comment]
Après, bug or feature, i on avait un mode démonstration de PL abusant de ce non contrôle, ça pourrait être cool.

**Comment by nimdanor** [comment]
IL faut donc que l'activité puisse être déclaré ouverte/fermé.
Indépendement de l'activité c'est donc une propriété d'Asset.

**Comment by qcoumes** [comment]
Les activités peuvent être fermées / ouvertes depuis 0aa4c23b73c710ba664eae850bef1503a8818069, qui est sur master.
