### ISSUE TITLE
Ouverture de la doc dans un nouvel onglet

### ISSUE THREAD

**Issue by nimdanor** [PremierLangage/premierlangage#208]
Cela serait plus simple si la documentation s'ouvrait dans un nouvel onglet, car en général on souhaite lire la doc quand on est dans l'editeur...

**Comment by qcoumes** [comment]
Vous êtes sûr de vouloir forcer cela ? En général un clic de la molette (ou ctrl + clic) suffit.

Sinon @mciissee , il faut rajouter `target="_blank"` a la balise `<a>` me semble (même si je suis sûr que tu le sais déjà :smile:)

**Comment by nimdanor** [comment]
Oui quand tu est sous editeur tu click sur la doc c'est naturel il te demande si tu veux quitter le site ... c'est pas terrible et comme tu dit cela ne cout pas grand chose (mais les petits ruisseaux font les grande rivières).
