### ISSUE TITLE
Il faut ouvrir la participation à l'édition de la documentation

### ISSUE THREAD

**Issue by nimdanor** [PremierLangage/premierlangage#209]
Le cycle de mise a jour de la documentation est trops lent.
Il faut désolidariser une partie de la doc de programmation des exercices des versions de déploiement.
Il faut pouvoir déployer la doc sans déployer de nouvelle versions du code.
Il y a un lien qui permet d'aller sur github pour modifier la doc mais il faut faire un pull request pour corriger une faute d'orthographe .....

Une doc dans un site externe avec readthedoc serait sans doute mieux.

**Comment by Pavell94000** [comment]
C'est fait ici https://documentationpl.readthedocs.io/fr/latest/ à partir du repo https://github.com/PremierLangage/documentationpl/
