### ISSUE TITLE
Conflict between jinja2 and django templates

### ISSUE THREAD

**Issue by ddoyen** [PremierLangage/premierlangage#214]
In some of my PL exercises, I use jinja2 templates in some keys (that are rendered with a suitable script in the builder).

But when the keys are rendered as django templates with playexo/models.py, it can cause syntax errors.

Is there a way to fix that ? Shoud I avoid using jinja2 templates ?

**Comment by nimdanor** [comment]
No we should use jinja2 every where . 
But what is the différences you have found ?

**Comment by ddoyen** [comment]
I wanted to use the following kind of loop.

~~~
{% for i in range(n) %}
...
{% endfor %}
~~~

This syntax is supported by jinja2 but not by django. 

Finally, I found a way to do it differently.

**Comment by nimdanor** [comment]
If jinja2 is better it should be the template engine used in premierlangage.
@qcoumes when you will have the time can you please look into using jinja as the template engine.

**Comment by ddoyen** [comment]
Macros are not available in django templates.

**Comment by nimdanor** [comment]
We must use Jinja as the template engine. @Pavell94000 can you look at this.
(not tomorow obviously)

**Comment by nimdanor** [comment]
https://medium.com/@samuh/using-jinja2-with-django-1-8-onwards-9c58fe1204dc
this post explaines what to do.
