### ISSUE TITLE
Get answers by name instead of id

### ISSUE THREAD

**Issue by ddoyen** [PremierLangage/premierlangage#215]
Here is the function that catches answers in playexo.js. Wouldn't it be better to use name instead of id ? With this function, the radio and checkbox input elements are implied to share the same id...

~~~
function getInputs(){
    let inputs = {};
    $( "[id^='form_']" ).each(function() {
        let id = this.id.slice(5); // name of the variable
        let value = $(this).val();
        if ($(this).is(':radio')) {
            if($(this).is(':checked')) {
                inputs[id]=value;
            }
        }
        else if ($(this).is(':checkbox')) {
            if($(this).is(':checked')) {
                if (id in inputs) {
                    inputs[id].push(value);
                }
                else {
                    inputs[id] = [value]
                }
            }
        }
        else {
            inputs[id]=value;
        }
    });
    return inputs;
}
~~~

**Comment by nimdanor** [comment]
I dpn't see the advantage of using name agains id ? 
id are supposed to be uniq ?

**Comment by ddoyen** [comment]
Indeed, the radio/checkbox elements can share the same name but should have different id.

**Comment by ddoyen** [comment]
Here are some problems with radio/checkbox elements sharing the same id:
* one cannot use "label" elements since they are bound to an id;
* one cannot use "getElementById" method (to color the right and the wrong answers using a JS script for instance).

**Comment by nimdanor** [comment]
This must be done with a synchronisation of all the exercices of conceptexo. 
This must be in the nexst realease.

**Comment by ddoyen** [comment]
It is no longer a problem with components.
