### ISSUE TITLE
github acces from pl

### ISSUE THREAD

**Issue by nimdanor** [PremierLangage/premierlangage#218]
The login for all access tp github from pl*.u-pem.fr should be define in the setting,
preferably with a ssh id. Or with the plgitlogin account.

**Comment by nborie** [comment]
...
I do not know how this could be related to my problem : I have to provide credentials to push to Osbank
"Repository is private, please provide credentials"
I did search in severals place (click all buttons and everywhere in the editor, documentation, profile page, ...) but I really do not know how I can provide the credentials for this github repository inside the editor.

**Comment by mciissee** [comment]
If you just want to provides credentials (login + password) this feature is added in the 0.5.3 version available on pl-test4.u-pem.fr

**Comment by nborie** [comment]
Perfect for me : same servor (preprod) and same login. When I did try to re push, the small frame for credential did pop and the the 3 commit did reach osbank git repo.

**Comment by nimdanor** [comment]
good
