### ISSUE TITLE
[editor] doesn't accept - in file name 

### ISSUE THREAD

**Issue by nimdanor** [PremierLangage/premierlangage#221]
in a file i can't CTRL-Click this link :
extends=/python-pl-bank/template/pltest.pl 

error message 
Impossible to resolve the path '../../python' :
 - File '../../python' does not exists

**Comment by mciissee** [comment]
Where is located the file ?

**Comment by nimdanor** [comment]
conceptexo/ESSAIS/mathias/

**Comment by mciissee** [comment]
This directory does not exists on pl-preprod
