### ISSUE TITLE
Visual feedback ?

### ISSUE THREAD

**Issue by esandier** [PremierLangage/premierlangage#225]
It would be nice to be able to paint or display differently some `html` elements in the `form` and `text` tags of a `pl` after analyzing the answer, in the `evaluator` part of the exercise. This would allow to implement more fun and visual types of feedbacks, and even animations using `css`.

**Comment by mciissee** [comment]
This is already possible by adding a <style></style> tag inside the text or form tag and returning an html feedback with class or id selectors targeting your styles.

**Comment by mciissee** [comment]
If you want to execute an action only after the evaluation of your answers you can declare the following function inside the form tag 
```
function onAfterSubmitPL() {
}
```
The function will be called automatically for you and you can modify the html page.
There is also the function  **onBeforeSubmitPL()** called after the submit button is clicked.

**Comment by ddoyen** [comment]
Here is a suggestion. 

* The builder/evaluator should initialize/update variables that indicate the "exercise mode" (first try, retry, frozen with correction, frozen without correction, etc.).
* The form and text then just need to be jinja templates depending on these variables (with "if" conditional structures).

That's what I have experimented with JSXGraph exercices. I fix a maximum number of attempts and, after the last attempt, the JSXGraph board is frozen and the solution is displayed.

**Comment by esandier** [comment]
@mciissee : How does the evaluator pass arguments to onAfterSubmitPL ?

**Comment by nimdanor** [comment]
I don't think we should go down this path.
Changing the look of your exercice should be done b changing the values of form and text in the evaluator.

Not by applying javascript code,
this wouldl augment the size of the API a thing we don't want to do ...

In the evaluator the state or time of the exercice can be changed with out any intervention from the server.

**Comment by nimdanor** [comment]
the feedback MUST contain all the html you want without having to add anything (responsabilities) to the server.

**Comment by esandier** [comment]
I'm a bit confused, how would you change the baground color of an html element in `form` to green or red according to whether the answer to the exercise is right or wrong?

**Comment by mciissee** [comment]
@esandier The solution that I can suggest for now is the following: 

- inside the evaluator tag 
    ```
arg = {
        "str": "...",
        "int": 10,
    }
    grade=(100, '{0} <input id='myid' type="hidden" value="{1}">'.format('Good', arg))
```
- inside the onAfterSubmitPL function
function onAfterSubmitPL() {
   const response = JSON.parse($('#myid').val());
// 
}

**Comment by mciissee** [comment]
If you don't want to return a JSON string you can replace arg = {...} by arg = 'true' or arg = 'false'
and use a simple equality operator inside onAfterSubmitPL function
```
if ($('#myid').val() === 'true') {
} else {
}
```

**Comment by nimdanor** [comment]
Voici ce que je fait pour afficher le feedback d'un qcm 
en rouge les mauvaise réponses, strikethrue si il ne fallais pas la cocher 
en vert les bonne réponses, strikethrue si il ne fallais pas la cocher 


```python
def redTd(b,txt):
    if not b:
        txt = '<del>'+txt+'</del>'
    return '<TR><TD><div class="btn-danger"> '+txt+' </div></TD</TR>'
    
def greenTd(b,txt):
    if not b:
        txt = '<del>'+txt+'</del>'
    return '<TR><TD><div class="btn-success"> '+txt+' </div></TD</TR>'



def createshowanswer(enonce, studentdic):
    """
    :param enonce: [(" affirmation1",True),("affirmation2",False],(" affirmation3",True),("affirmation4",False],]
    :param studentdic: ["anwser_1":['on'], "anwser_2":['on']]
    :return:
       a html table with green TD if crosed and good or not crosed and bad
       else a red TD 
    """
    
    form="<table>"
    for i,(x,b) in enumerate(enonce):
        q='answer_'+str(i)
        if (b and q in studentdic) or (not b and not q in studentdic):
            form += greenTd(b,x)
        else:
            form +=redTd(b,x)
            
    form +="</table>"
    return form
```

**Comment by nimdanor** [comment]
Mamadou aime trop le javascript. 
D'autre part je veux pas qu'il y ai du code qui modifie le feedback entre le moment ou l'on défini le grade et le moment ou le feedback est affiché à l'apprenant. 
Cela rentrerai en conflit avec le code des ACTIVITE qui doit définir si le feedback doit être fait ou pas.

Donc pouvez vous vous orientez vers un package python qui fabrique le feedback que vous voulez,
avec les élements graphiques et les varaiables de style gérée dans ce module python feedback.

**Comment by ddoyen** [comment]
Another way is to use conditional structures in the jinja template defining the form and render this template with the suitable context in the evaluator.

Building html by concatenating strings in a python script can be a bit tedious, imho.

**Comment by esandier** [comment]
@mciissee : I inserted this in the `form` tag of my `pl`
~~~~
<script>
function onAfterSubmitPL() {
    console.log("coucou"); 
}
</script>
~~~~
but nothing happens on the console. Is there something I dont understand?

@ddoyen and @nimdanor : I still don't understand how you modify the form from the evaluator.  But we can discuss it someday.

**Comment by mciissee** [comment]
It should log the message on the browser console after you submit your form.
Where is located the file that I can test it?
If you want to see an example that use it, look at the files **conceptexo/Chemistry/templates/template.html** **conceptexo/Chemistry/exercices/interrogation/cram.pl**

**Comment by esandier** [comment]
The file is there, I'll check your example
~~~~
https://pl.u-pem.fr/filebrowser/option?name=test_pl&path=Yggdrasil/maths-pl-bank/exercises/matrices/essaiOnAfterSubmit.pl
~~~~

**Comment by mciissee** [comment]
It's not working because this feature is added only on the version of PL at [](https://pl-preprod.u-pem.fr)

**Comment by mciissee** [comment]
https://pl-preprod.u-pem.fr

**Comment by esandier** [comment]
@mciissee : indeed it works on preprod. One last question: i did not understand the code 
~~~~
form==
function onAfterSubmitPL() {
   const response = JSON.parse($('#myid').val());
}
==

evaluator==
arg = {
"str": "...",
"int": 10,
}
grade=(100, '{0} '.format('Good', arg))
==
~~~~
what is `myid` and why does its value contain `arg`?

**Comment by mciissee** [comment]
`grade=(100, '<input type="hidden" id="myid" value="{0}" /> '.format(arg))`

**Comment by nimdanor** [comment]
Modification de form dans le grader 
https://github.com/nimdanor/python-pl-bank/blob/master/template/qcm_evaluator.py

**Comment by esandier** [comment]
It works, Thanks!

**Comment by esandier** [comment]
here is the result
`https://pl-preprod.u-pem.fr/filebrowser/option?name=test_pl&path=Yggdrasil/maths-pl-bank/exercises/matrices/matrice_antisymetrique.pl`
