### ISSUE TITLE
Image de theme 

### ISSUE THREAD

**Issue by nimdanor** [PremierLangage/premierlangage#226]
Pour égayer le site il faudrait avoir une image de thème qui fait le fond de la div TITLE.

Noël / Citrouilles / la rentrée / les exams

**Comment by mciissee** [comment]
Je pense que cela devrait être un choix de chaque utilisateur d’appliquer ou non une image de theme et cela est possible en utilisant les callbacks qui sont dans playexo.js

Par ailleurs cette issue est liée à la #137 et la #162
