### ISSUE TITLE
Value of seed

### ISSUE THREAD

**Issue by nimdanor** [PremierLangage/premierlangage#230]
What is the value of the seed in the case there is no builder ?
can we set a standard value = -1, and can we set that a seed must be a positive number ?
What is the default value of the seed ? Is it always random ?

**Comment by Pavell94000** [comment]
The seed is time if there is no builder

**Comment by nimdanor** [comment]
So allways Huge and positive 
could you change this to time modulo 1000.

**Comment by Pavell94000** [comment]
Ok, it will be in 0.6.0
