### ISSUE TITLE
bug in editor?

### ISSUE THREAD

**Issue by esandier** [PremierLangage/premierlangage#238]
One of my exercises made the editor stall for a long time `produit_matrices.pl`. I could detect that it was a single erroneous  line of code in the `evaluator` tag of the exercise which caused the problem
~~~~
input_resizable_matrix_matrice = ok_answer = json.dumps(ok_answer)
~~~~
There was the same problem, caused by the same line in `ULmatrix.PL`.

Both are corrected now, but the behaviour seems strange to me.

**Comment by mciissee** [comment]
I could not reproduce this issue.
Is the bug still occurs when you open the file `produit_matrices.pl` or `ULmatrix.PL` ?

**Comment by esandier** [comment]
yes, i just tried to put back the line 
~~~~
input_resizable_matrix_matrice = ok_answer = json.dumps(ok_answer)
~~~~
in `ULmatrix.pl` and it immediately made the editor stop. I saved the file with the line, you can try it.
