### ISSUE TITLE
Preview and exercice by it's id in the database

### ISSUE THREAD

**Issue by nimdanor** [PremierLangage/premierlangage#240]
i need a   pl.u-pem.fr/playexo/direct/<int:pl_id> that permit's to test an exercice that was loaded but as disappeared in the editor.

**Comment by nimdanor** [comment]
this could be done without being logged in ?

**Comment by mciissee** [comment]
`Implemented` in #329

You can preview anonymously a pl already loaded by replacing the last part (PL_ID) of the following url https://pl.u-pem.fr/filebrowser/demo/PL_ID by the id of the pl.
