### ISSUE TITLE
Server error 500

### ISSUE THREAD

**Issue by nimdanor** [PremierLangage/premierlangage#241]
Nous avons fait une tentative avec le server moodle de l'unviersité de Tours et nous avons eu comme seul réponse 
serveur error 500 
@qcoumes peut tu faire un point avec N.Cuvelier pour extraire des logs ce qui n'a pas fonctionné dans le LTI 
ou faire un point avec esandier sur les modalités d'accès en LTI à pl 
Merci
Dominique

**Comment by esandier** [comment]
@qcoumes. Je serai à Marne lundi, je suis dispo en début d'après midi.

**Comment by esandier** [comment]
J'ai vu quentin, et tout marche, on avait du mal s'y prendre
