### ISSUE TITLE
Export the score card of an activity 

### ISSUE THREAD

**Issue by nimdanor** [PremierLangage/premierlangage#243]
export a csv/excel file of first,last, studentid, score, whatelse for every student for a given activity

Should be treated with a view in classmanagement or stats ??.

**Comment by nimdanor** [comment]
Yes !
tu fait aussi la version pour l'ensemble des activités d'une activité (avec un visiteur ;)

**Comment by Pavell94000** [comment]
Ca  doit être fait par l'activité qui s'occupe d'en regrouper d'autres (donc le cours et les sections dans notre cas) Il suffira d'appeler récursivement les notes des sous activités, donc pas de problèmes pour ca.
Il reste à déterminer comment choisir le barem selon l'activité, Cette [issue](https://github.com/PremierLangage/premierlangage/issues/39) en parle déjà, c'est pour ça que j'ai fermé celle ci qui ne demande qu'un bouton pour récupérer le csv (ce qui est déjà implémenté du coup)
