### ISSUE TITLE
text (template) is not reevaluated after grading

### ISSUE THREAD

**Issue by nimdanor** [PremierLangage/premierlangage#248]
La balise Text n'est pas réévalué après le passage du grader.
This should be check with a automatique TEST !!!!

I asked for a functionnal test last YEAR.

Properties like this one is a NECESSITY with out reevaluation a lot of exercices are impossible  .

so
we need a TEST @Pavell94000 
a debug Version @mciissee 
an installation !! @qcoumes

**Comment by mciissee** [comment]
linked to #239 and fixed on `fix-239 branch`

**Comment by nborie** [comment]
IMO, this may be related to #130 ...

**Comment by nimdanor** [comment]
we  need a TEST @Pavell94000

**Comment by Pavell94000** [comment]
It's a work in progress on the [177_splinter_test](https://github.com/PremierLangage/premierlangage/tree/177_splinter_test) branch, but we had a lot of work the last 2 weeks with the 0.6 release

**Comment by nimdanor** [comment]
ok it's a first priority all the time 
WE MUST BE ABLE TO MAKE A SAFE RELEASE
The release rules must be updates with a set of manual tests.

1) creation of a branch called RC (release candidate) with a number 0.X.Y for the time beeing so next one if RC0.6.0 
2) the push rules of master must be applied to push to RC,  i.e.  two review 
3) The RC must be deploied on plpreprod.
Manual tests  in lib/tests/manual/ must be done:
- all pl tests (running pls)
- all pltp tests (running pltp) 
- all activities  tests (running activities)
- all editor tests (checking the 
- all moodle tests  
If everything pass then the RC is push on the master 
4) The master is pushed on the production.

**Comment by nimdanor** [comment]
I hope the exams are gooing smooovely :)
