### ISSUE TITLE
Demonstration mode for some PL exercises/activities

### ISSUE THREAD

**Issue by nthiery** [PremierLangage/premierlangage#25]
Use case: I just wrote some experimental exercises for our 1st year students in Orsay. Now I would like to show them to the colleagues that are teaching this class with me (20 of them!), so that we can start discussing the adoption of PL, compare with our previous WIMS solution, ... Ideally, I would just provide them with just a URL that they could follow to play directly with the exercise(s).

In general, letting people search and access individual exercises and forward them to colleagues would be a strong mean to advertise the platform. There are some security issues -- mostly risks of deny of service attacks -- that should be not too hard to handle; typically by running the anonymous server in a separate machine, or just throttling the amount of anonymous access.

**Comment by nimdanor** [comment]
anonymous access should be given specificaly. By default sources of exercices are accessible only to logged staff.

**Comment by nthiery** [comment]
I should have been more specific: I meant anonymous access to the exercise in action, so that they can play with it; not the sources (for that, I can point them to my git repo :-) )

**Comment by nimdanor** [comment]
https://elearning.u-pem.fr/course/view.php?id=4476
guest access :  EssoxLucius1 
Password: EssoxLucius1

**Comment by nborie** [comment]
As we discussed a bit with the boss, this will be called the Demonstration Mode (perhaps a decorator of activity will be enough). A resource activity in Demonstration Mode do not required authentication, give an access to play the resource only (the playexo cycle only : build --> display --> form --> grade --> feedback --> grade --> feedback --> grade --> feedback --> etc...)

* Does this kind of resources need logs in database ? (not a so bad question... I think yes for survey : a kind of exercise on which you really want the stat...)

* How to tell PL that the activity is in demonstration mode ? (a decorator of activity ? A special directory with identified name allowed in all repository ? another idea ? ...)

* Is there potential problem if URL of these exercises are indexed ?

* What is the policy (spread of hide) with such easy access to PL ressources ?

I currently think that easy access is always better, especially for non commercial pedagogical resources. Anyway, this has to be well designed before spreading everything in all direction.

A lot of potential users (like the Euler group near Versailles...) would find great benefits in this possibility of demonstration. It will be not only used to show off behind coworkers for convincing them to use PL. 

But the design of this demonstration mode make popping an another question : How PL (the web site...) look like for a non connected user ?

We definitely need to display more information on https://pl.u-pem.fr/courses/login/ when not connected. Also, the documentation should be ALWAYS available even someone has no access to PL.

**Comment by mciissee** [comment]
fixed in #329
