### ISSUE TITLE
New operators in PL syntax

### ISSUE THREAD

**Issue by nimdanor** [PremierLangage/premierlangage#250]
A = toto
A -= Monsieur 
A += n'a pas appris son cours.
A -= C'est pas sérieux.

Construit la phrase : 
C'est pas sérieux.  Monsieur toto n'a pas appris son cours.

**Comment by nimdanor** [comment]
This should be done with the bug repport that  += is not working 
This should be done with the new operator   $=
```
imagename $= pathvalue
```
that permits to create a file visible on the server (not the sandbox as @)
and create the variable name with the value of the url giving access to the file 
usage :
```
<img  src="{{imagename}}" >
or 
( Text of link)[{{imagename}}]

**Comment by mciissee** [comment]
in the current implementation of the parser += operator is a multiline key: 
```
A += 
...
==
```
instead of 
`A += ...`

Is the new operator -= should be a multiline key also?

**Comment by nimdanor** [comment]
Yes 
is there an + operator (mono line ?? ) if yes let's have a monoline - operator 

in any case += and -= are multiline
good remark ;)

**Comment by mciissee** [comment]
Yes there is a online operator - 
What about the operator +=@ ? Is an equivalent -=@ should be added ?

**Comment by nimdanor** [comment]
Yeah shouldn't be to difficult ;)

**Comment by mciissee** [comment]
already done in the new version of PL $= is replaced by =$ so I think that this can be closed @nimdanor? The documentation should be updated.
