### ISSUE TITLE
A view  to test compilation of a pl

### ISSUE THREAD

**Issue by nimdanor** [PremierLangage/premierlangage#252]
I need a new view in filebrowser views for the pltutorial.

a get view 
"compile_text_at"
that needs a thepl="the pl file as text" 
and a  path= the directory where the exercice is suppose to be if it was a file.

**Comment by mciissee** [comment]
Could be implemented easily by changing compile_pl view in filebrowser app but I think that the pl string could not contains reference to another files using the @ operator and the request must be a POST request only.

**Comment by nimdanor** [comment]
To be able to create nice exercices it should be possible to tell where the virtual file is located.
So we can use a Mathematics or a Chemistery exemple in the pltutorial.

The references by the @ will use the path parameter given in the request as the "." directory.

**Comment by mciissee** [comment]
Can you give an example of pl code to compile including the @ operator ?

**Comment by plgitlogin** [comment]
the view is a post 
 filebrowser.pl_tuto
with 
student=" le fichier pl a tester"
resultat 
un dictionnaire avec compile= true or false
json = dictionnaire résultant 
warnings= les warnings
