### ISSUE TITLE
CI: Use travis-ci.org instead of TeamCity

### ISSUE THREAD

**Issue by qcoumes** [PremierLangage/premierlangage#258]
Was thinking of migrating our CI from TeamCity to [travis-ci](https://travis-ci.org/) as our current build on TeamCity has many disadvantages :

* Written in Java.
* Is on pl-preprod.
* Is not integrated with github.
* Written in Java.
* Run in dockers (and running dockers in docker for the sandbox means a lot of hack)
* We have to update the sandbox manually.
* Free version of TeamCity cannot run multiple test at once.
* Did I mention it was written in Java ?

So if everyone is OK, I think we should move to Travis as soon as possible.

@nimdanor @nborie @Pavell94000 @mciissee

**Comment by Pavell94000** [comment]
With the addition of front-end tests, it will be way easier to use Travis instead of TeamCity.

**Comment by nimdanor** [comment]
I have no problem with the change.
