### ISSUE TITLE
Video

### ISSUE THREAD

**Issue by plgitlogin** [PremierLangage/premierlangage#264]
We need the possibility of having resources of type video, and to be able to include a video in an exercise.
- upload / save / access
- how to documentation for resource and inclusion.

**Comment by mciissee** [comment]
For uploading a video you can drag It from your filesystem to the editor explorer as for any resources.

To use the video in your exercise, you must use the =$ operator like I did in the following example :  

https://pl.u-pem.fr/filebrowser/option?name=test_pl&path=Yggdrasil/ComputerScience/python/AP1-1920/drafts/dominique/video.pl
