### ISSUE TITLE
Input Tags

### ISSUE THREAD

**Issue by mciissee** [PremierLangage/premierlangage#270]
At the end of a meeting with @nimdanor @esandier  @ddoyen , it was decided to create a new tag system for PL forms.

**Components:**
A tag must be composed of 3 parts:

- A python part represented by a class that defines the properties of the tag (text, color, active, visible, value, disabled...). The class must be serializable to a JSON object to be able to be used with JS code.

- An HTML-CSS part to display a tag in a form using the serialized JSON of the python class

- A JS part allowing to control dynamically the display of the tag by making the link between python and HTML (the JS send the value of the tag to python and python indicates to the JS in which state the tag should be in the html).

**Lifecycles: **

Tags must be created inside the before== key.

```
before==
mytag = MyTagClass()
mytag.someproperty = 10
mytag.anotherproperty = 'ddjn'
...
==
```

Tags must be inserted in the html inside the form== key

```
form=
{{mytag}}
==
```

Tags must be processed in the evaluator== key
```
evaluator=
# answer['mytag'] is added to the answers at the submission
# by a call to mytag.value() in playexo.js script.
# mytag.setState(state) will update the properties of the python class.

mytag.setState(answer['mytag'])
==
```

**Comment by qcoumes** [comment]
What if we want to use another grader than `before.py`

**Comment by nimdanor** [comment]
We can write in a  grader:
dic['mytag']= MyTagClass()

**Comment by esandier** [comment]
A python class looks good to me. 
Just to make sure i understand:
At submission, playexo.js calls mytag.value(), and returns the value to the view.
What i don't see  in your description is a javascript mytag.setState(parameters) called by playexo.js when the grader returns the result (for instance success). This is needed to visually update the tag, right?
Etienne
    Le jeudi 30 mai 2019 à 12:35:24 UTC+3, Mamadou Cisse <notifications@github.com> a écrit :  
 
 
At the end of a meeting with @nimdanor @esandier @ddoyen , it was decided to create a new tag system for PL forms.

Components:
A tag must be composed of 3 parts:
   
   -    
A python part represented by a class that defines the properties of the tag (text, color, active, visible, value, disabled...). The class must be serializable to a JSON object to be able to be used with JS code.

   -    
An HTML-CSS part to display a tag in a form using the serialized JSON of the python class

   -    
A JS part allowing to control dynamically the display of the tag by making the link between python and HTML (the JS send the value of the tag to python and python indicates to the JS in which state the tag should be in the html).


**Lifecycles: **

Tags must be created inside the before== key.
`
before==
mytag = MyTagClass()
mytag.someproperty = 10
mytag.anotherproperty = 'ddjn'
...

Tags must be inserted in the html inside the form== key
form=
{{mytag}}

`

Tags must be processed in the evaluator== key
`
evaluator=

answer['mytag'] is added to the answers at the submission

by a call to mytag.value() in playexo.js script.

mytag.setState(state) will update the properties of the python class.

mytag.setState(answer['mytag'])

`

**Comment by mciissee** [comment]
At submission, playexo.js will call tag.value() for each tag in the html and store the JSON in answer[tag.id or tag.name]. 

For example, the server could be called with a JSON like the following
```
answer = {
  'mydndtag': { 'drop': '....' },
  'mycheckboxtag: { 'checked': true  },
  'myinputtag: { 'text': '....' },
  ...
}
```
inside the evaluator key, a call to the python method mydndtag.setState(answer['mydndtag']) will let the tag check itself if the answer is good or not and returns also a JSON example:
```
{ good: true, extradata: ... } 
```

After the evaluation the method mytag.setState(response['mytag']) will be called for each tag in JS side also with the value returned by the python class. Each tag could update it's visual state at this moment according to the response of the server.

**Comment by esandier** [comment]
I think the tag cannot in general decide by itself whether the answer is correct or not. This can be a complex thing  (for instance "enter a 3x3 symmetric matrix"). It could also involve the input of several tags.
I think the python class should only store visual information, and also translate python/sympy data to json data and back. 
Etienne
    Le samedi 1 juin 2019 à 11:17:14 UTC+2, Mamadou Cisse <notifications@github.com> a écrit :  
 
 
At submission, playexo.js will call tag.value() for each tag in the html and store the JSON in answer[tag.id or tag.name].

For example, the server could be called with a JSON like the following
answer = {
  'mydndtag': { 'drop': '....' },
  'mycheckboxtag: { 'checked': true  },
  'myinputtag: { 'text': '....' },
  ...
}

inside the evaluator key, a call to the python method mydndtag.setState(answer['mydndtag']) will let the tag check itself if the answer is good or not and returns also a JSON example:
{ good: true, extradata: ... } 

After the evaluation the method mytag.setState(response['mytag']) will be called for each tag in JS side also with the value returned by the python class. Each tag could update it's visual state at this moment according to the response of the server.

**Comment by mciissee** [comment]
Is the form should be reloaded by playexo.js script after the grade (this is the current behaviour) or a method should be called for every tag in the html after the grade then each tag will change it’s visual state according to the answer of the server? @nimdanor

**Comment by esandier** [comment]
I think a method should be called for every tag. It is visually nicer.

Étienne

**Comment by nimdanor** [comment]
@mciissee and @esandier  i don't see any reason to choose one or the other, i don't see the visual effects. 
**Be very carefull of the need of the exam activity where we don't want ANY feedback that may give the answer to the student ** the feedback must be a togglable optional.


We need a basic creation of an input tag outside of "before" or "builder", the following pl syntax  should do the trick.
```
mytag ?= MyTagClass
```
this will create a tag like following  line in before : 
```
mytag = MyTagClass()

```

**Comment by ddoyen** [comment]
I'm ok with this operator for defining input tags in a PL exercise.

**Comment by ddoyen** [comment]
Here is a list of basic input tags:

- Text
- Numeric
- Radio
- Checkbox
- SortList
- DragDrop
- SelectWord
- JSXGraph
- MathExpr
- CodeEditor

**Comment by mciissee** [comment]
Components are now available on pl-preprod. You can start using them.

The documentation is hosted inside the editor  (on the sidebar). There is many examples  in the documentation, I suggest you to read entirely the 3 first pages because I added  new important features like the components operator that made the creation of components very easy

**Comment by mciissee** [comment]
Please let me know if something in the documentation is not working

**Comment by esandier** [comment]
Thank you Mamadou,
I'll start looking monday.
Etienne
    Le mercredi 17 juillet 2019 à 19:13:36 UTC+2, Mamadou Cisse <notifications@github.com> a écrit :  
 
 
Components are now available on pl-preprod. You can start using them.

The documentation is hosted inside the editor (on the sidebar). There is many examples in the documentation, I suggest you to read entirely the 3 first pages because I added new important features like the components operator that made the creation of components very easy

**Comment by ddoyen** [comment]
I've started to look at the components. Nice work !

But I cannot retrieve the value of a MathInput component. I have the following error :

~~~
AttributeError: 'MathInput' object has no attribute 'value'
~~~

I'm using the server pl.u-pem.fr

**Comment by mciissee** [comment]
This seems to be a  python error.  Is the example on the tutorial page showing the same error? It is possible to show me a screen of the code?

**Comment by ddoyen** [comment]
I'm just trying the example given in the documentation.

https://pl.u-pem.fr/components/math-input

**Comment by esandier** [comment]
Bonjour Mamadou,
je ne parviens plus à me connecter sur preprod. Avant je me connectais sur https://elearning.u-pem.fr et j'avais accès à preprod, mais maintenant il y a une page de connection pour preprod, et je ne sais pas quel login/mdp je dois utiliser
Etienne




    Le mercredi 17 juillet 2019 à 19:13:36 UTC+2, Mamadou Cisse <notifications@github.com> a écrit :  
 
 
Components are now available on pl-preprod. You can start using them.

The documentation is hosted inside the editor (on the sidebar). There is many examples in the documentation, I suggest you to read entirely the 3 first pages because I added new important features like the components operator that made the creation of components very easy

**Comment by mciissee** [comment]
Vous pouvez utiliser le login **admin** et le mot de passe **adminadmin** pour vous connecter sur pre-prod ou sinon vous pouvez aussi vous connecter sur pl.u-pem.fr les components sont aussi disponible sur ce serveur.

**Comment by mciissee** [comment]
> I'm just trying the example given in the documentation.
> 
> https://pl.u-pem.fr/components/math-input

Can you show me a screen of the page please (with the code and the preview).
A screen of your browser console can be useful also (F12)

**Comment by esandier** [comment]
OK merci!
    Le lundi 22 juillet 2019 à 16:15:51 UTC+2, Mamadou Cisse <notifications@github.com> a écrit :  
 
 
Vous pouvez utiliser le login admin et le mot de passe adminadmin pour vous connecter sur pre-prod ou sinon vous pouvez aussi vous connecter sur pl.u-pem.fr les components sont aussi disponible sur ce serveur.

**Comment by ddoyen** [comment]
> > I'm just trying the example given in the documentation.
> > https://pl.u-pem.fr/components/math-input
> 
> Can you show me a screen of the page please (with the code and the preview).
> A screen of your browser console can be useful also (F12)

Actually, it works on the pl-preprod server but not on the pl-server.

Here is the error on the pl server.
~~~
Une erreur s'est produite lors de l'exécution du grader (exit code: 1, env: test_c93cc77d-6894-41bd-bb05-ddffccbee4b4_built). Merci de prévenir votre professeur
Received on stderr:

Traceback (most recent call last):
  File "grader.py", line 44, in 
    exec(add_try_clause(dic['evaluator'], StopEvaluatorExec), dic)
  File "", line 2, in 
AttributeError: 'MathInput' object has no attribute 'value'
~~~

**Comment by mciissee** [comment]
Strange it's working for me on the two servers. If you just
preview the code of the example without any modification and if the browser console don't show an error it it should work.

Can you replace the code with the code above and check if 'value' is present on the list displayed after you click on submit button.

```
@ /utils/sandboxio.py
grader  =@ /grader/evaluator.py
builder =@ /builder/before.py

component =: MathInput
before==
==
title==
Math Input Component
==
text==
==
form==
{{ component|component }}
==
evaluator==
grade = (100, dir(component));
==

```

**Comment by mciissee** [comment]
I have another question. Is the syntax simple to understand? Have you understood how to extends a component with a custom class to provide an autocorrection like for the **ShortList** component?.

I think we should discuss about the **MathDrawer** and **MathInput** component to choose the way to use them (how to add a custom keyboard for the MathInput, What type of object the MathDrawer should return...)

**Comment by ddoyen** [comment]
No, value is not in the list.

~~~
['__class__', '__delattr__', '__dict__', '__dir__', '__doc__', '__eq__', '__format__', '__ge__', 
'__getattribute__', '__gt__', '__hash__', '__init__', '__init_subclass__', '__le__', '__lt__', '__module__', 
'__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', 
'__subclasshook__', '__weakref__', 'cid', 'deserialize', 'from_context', 'selector', 'sync_context'] 
~~~

**Comment by esandier** [comment]
Hello Mamadou, 
very nice job, I have tried the DragDrop yesterday. Here are my remarks so far:

 1) I had a problem changing the css in the evaluator 
````
dragIn.css = "error-state anim-flip" 
````
The error I get is "Object DragDrop does not support item assignment"

2) If I understand well, the component is a `dict` in the before tag, and an `object` in the evaluator tag. This could be confusing, is it possible that it be an `object` in the before tag as well? 

3) Regarding the style of the dragdrop elements, It is a bit complicated to have to define a style to change the dimensions, for instance. It would be nice to be able to set some simple ccs properties directly. Also, there should be a bit of padding, maybe 4 or 6px. Also, it appears that if the content is math between $$, a lot of vertical padding appears, which doesn't happen if math is between $%.

4) When moving dragdrop elements containing math, there is a small delay when dropping due to typesetting of the equations, I don't know if it can be avoided?

5) There is a strange behaviour if you drag a component to a drop zone, then from there to another drop zone or back to the origin. I think the behaviour should be: a component can be dragged from its original location to a drop-zone, and from there to its original location, and that's all.

6) There should be two types of drag-elements, either once or multiple. "once" means that when you drag it from it's original location, it disappears from it, so it can only be dragged to one place, "multiple" means that when you drag it from its original location, it still is there, so you can drag another copy, etc...

Finally, I did not really understand from the documentation how to extend the components. But I'm slow!

Sorry for the long message.

Etienne

**Comment by mciissee** [comment]
> No, value is not in the list.
> 
> ```
> ['__class__', '__delattr__', '__dict__', '__dir__', '__doc__', '__eq__', '__format__', '__ge__', 
> '__getattribute__', '__gt__', '__hash__', '__init__', '__init_subclass__', '__le__', '__lt__', '__module__', 
> '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', 
> '__subclasshook__', '__weakref__', 'cid', 'deserialize', 'from_context', 'selector', 'sync_context'] 
> ```

There is no reason that value is not present in the list. I tried the example on multiple browsers and the value is always present. You can try to run the example on another browser without modifying it (Just preview then submit).  I suggest you to open the browser console (F12) to check if there is any error with MathLive with your browser.

Is the problem occurs only with MathInput component?. @esandier do you have the same problem?

**Comment by esandier** [comment]
No I dont have this problem, the example above works well for me, `value` is present. I did not try other components appart from DragDrop, which has no `value` attribute.

**Comment by mciissee** [comment]
> Hello Mamadou,
> very nice job, I have tried the DragDrop yesterday. Here are my remarks so far:
> 
> 1. I had a problem changing the css in the evaluator
> 
> ```
> dragIn.css = "error-state anim-flip" 
> ```
> 
> The error I get is "Object DragDrop does not support item assignment"
> 
> 1. If I understand well, the component is a `dict` in the before tag, and an `object` in the evaluator tag. This could be confusing, is it possible that it be an `object` in the before tag as well?
> 2. Regarding the style of the dragdrop elements, It is a bit complicated to have to define a style to change the dimensions, for instance. It would be nice to be able to set some simple ccs properties directly. Also, there should be a bit of padding, maybe 4 or 6px. Also, it appears that if the content is math between $$, a lot of vertical padding appears, which doesn't happen if math is between $%.
> 3. When moving dragdrop elements containing math, there is a small delay when dropping due to typesetting of the equations, I don't know if it can be avoided?
> 4. There is a strange behaviour if you drag a component to a drop zone, then from there to another drop zone or back to the origin. I think the behaviour should be: a component can be dragged from its original location to a drop-zone, and from there to its original location, and that's all.
> 5. There should be two types of drag-elements, either once or multiple. "once" means that when you drag it from it's original location, it disappears from it, so it can only be dragged to one place, "multiple" means that when you drag it from its original location, it still is there, so you can drag another copy, etc...
> 
> Finally, I did not really understand from the documentation how to extend the components. But I'm slow!
> 
> Sorry for the long message.
> 
> Etienne

1-2. Component is a dict only outside of a python context so inside before and evaluator (a python context) context is always an Object. You can use type(component) to check the type by. yourself so `dragIn.css = ...` should work if dragIn is a component (created with =: operator or by yourself).

3-4. Actually the only way to define css of a component is to use extra class in .css property. I suggest you to define your custom style that you always include. I made this choice because @nimdanor want component to provide a feedback only if outside of exam mode. By exposing css properties it will be difficult to handle components states in exam mode.
Concerning the MathJax delay this is normal because I need to wait a little delay to refresh MathJax after an element is moved in the page.

5-6. I will think about Drag Drop behaviors later.

**Comment by mciissee** [comment]
I you want to extends a component.

1. create a python file anywhere example **mycomponent.py**
2. create a python class extending one of the default components inside the file. The name of the class should be  in CamelUpperCase format. You can look the file class SortList inside the **lib/components/component.py**. I show you an example of class extending the default Component class.
3. to tell the framework you want to extend a component, you need to include the custom component file on the sandbox @mycomponent then assign the name MyComponent to the property **decorator** of the component you created as in the example from the doc.

If it is not clear, I can create an example on pl editor to show you.

**Comment by esandier** [comment]
Thanks, i'll try later today or tomorrow. About item 1, I do get an an error 
````
'dict' object has no attribute 'content'
````
if i try the assignment 
````
drag1.content = 'something'
````
in the before tag, where `drag1`is a component. But the following works. 
````
drag1['content'] = 'something'
````

**Comment by ddoyen** [comment]
> > No, value is not in the list.
> > ```
> > ['__class__', '__delattr__', '__dict__', '__dir__', '__doc__', '__eq__', '__format__', '__ge__', 
> > '__getattribute__', '__gt__', '__hash__', '__init__', '__init_subclass__', '__le__', '__lt__', '__module__', 
> > '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', 
> > '__subclasshook__', '__weakref__', 'cid', 'deserialize', 'from_context', 'selector', 'sync_context'] 
> > ```
> 
> There is no reason that value is not present in the list. I tried the example on multiple browsers and the value is always present. You can try to run the example on another browser without modifying it (Just preview then submit). I suggest you to open the browser console (F12) to check if there is any error with MathLive with your browser.
> 
> Is the problem occurs only with MathInput component?.

Same error with other components.

But, with Chrome, it works (I was using Firefox).

**Comment by ddoyen** [comment]
When using Firefox, I have this warning in the brower console when the exercise is loaded.

~~~
TypeError: asm.js type error: unsupported expression
~~~

Don't know if it helps.

**Comment by mciissee** [comment]
> Thanks, i'll try later today or tomorrow. About item 1, I do get an an error
> 
> ```
> 'dict' object has no attribute 'content'
> ```
> 
> if i try the assignment
> 
> ```
> drag1.content = 'something'
> ```
> 
> in the before tag, where `drag1`is a component. But the following works.
> 
> ```
> drag1['content'] = 'something'
> ```

Can you paste your code here or create a pl file that I can test (you can copy the link of file from the editor file explorer by right clicking on the file or by clicking on the link icon that appears when you hover the file)?

**Comment by mciissee** [comment]
> When using Firefox, I have this warning in the brower console when the exercise is loaded.
> 
> ```
> TypeError: asm.js type error: unsupported expression
> ```
> 
> Don't know if it helps.

If its work on Chrome the problem is caused by the version of firefox you are using. You should update it. Please tell me what version you are using I will try to check components with this version.

Another important thing components works only with before and evaluator graders/builders. If you want to use them with your own builders or graders you should call the function get_context() of sandbox.py from the beginning of your script. This will enable components for your scripts.

**Comment by esandier** [comment]
here is the [code](https://pl-preprod.u-pem.fr/filebrowser/option?name=test_pl&path=Yggdrasil/Mathematics/exercises/components_essais/essai_dragndrop.pl)

**Comment by mciissee** [comment]
I modified the code for you and as I said before and in the doc to use components with your own component you must get the context sys.argv[1] by calling the function sandboxio.get_context() because this function will enable components for the exercise. This is done by default for the standard keys **before** and **evaluator**. I modified the lines 5 and 71 of the file **home/builder/before2.py** for you It should work now.

**Comment by mciissee** [comment]
Another remark. The good way to evaluate the DragDrop component is to use the properties **droppedId** and **cid**. Comparing contents could be false because in the case of MathJax for example, content value is a text between $$...$$ inside before but inside evaluator content is the html code generated by MathJax so if you store content in a variable in before and use this variable in the evaluator the result will be always false.

**Comment by esandier** [comment]
OK, thank you

**Comment by mciissee** [comment]
I simplified the code you in the file essai_dragndrop2.pl. You can compare the two codes.

1. What I means by you cannot use components inside a list or dict from the doc is that currently if you add a component in a list, the element in the list will not be updated inside evaluator so if you don't use the list in evaluator, you can add the components in a list like I did in the simplified version.

2. You can access directly the cid of the components instead of using other variables 'id_in' and 'id_subset' because  cid will never change when you drag components only droppedId will change.

3. I think that you can extend the DragDrop component to provide an auto correction like for the SortList component.

**Comment by esandier** [comment]
Yes, I avoided the list because of the remark in the doc, using lists makes things much simpler!

**Comment by esandier** [comment]
I tried writing an extension of CheckboxGroup [here](https://pl-preprod.u-pem.fr/filebrowser/option?name=test_pl&path=Yggdrasil/Mathematics/exercises/components_essais/essai_extend.pl)

However my testing could not go very far because of this error
`````
ImportError: No module named 'checkboxrandom'

**Comment by mciissee** [comment]
I modified the code for you by adding comments in uppercase.

1. the name of the file contains a class should be the same as the class name in lowercase without any special character (CheckboxRandom -> checkboxrandom)

2. you cannot use get method inside a component class since a class does not have a method 'get' this is a method of a dict object.

3. instead of dynamically checking the presence of a property using getattr or setattr you must declare  the properties in the constructor with the default values and BEFORE super.__init__(**kwargs) THIS IS VERY IMPORTANT AS EXPLAINED IN THE COMMENTS

4. you can use local variables instead of declaring a property for variables you use only in a method.

5. **properties of a component should starts with an underscore as explained in the doc otherwise a student could open the browser inspector and see all the properties you declare in your class as explained in the doc.**

**Comment by esandier** [comment]
Thank you for the comments, it is clear for me now. I am on holidays so I will not look at this for a couple more days.
