### ISSUE TITLE
[dev/ops] version en ligne

### ISSUE THREAD

**Issue by nimdanor** [PremierLangage/premierlangage#272]
La version en ligne sur pl.u-pem.fr est la 0.6.1
La version en ligne sur pl-preprod.u-pem.fr est la 0.6.1
pourtant elles ne se comportent pas de la même façon ... ?

**Comment by nimdanor** [comment]
Enfin j'ai besoin d'une version à jour sur pl.u-pem.fr et que preprod ne soit plus utiliser par d'autres utiilisateurs que l'équipe de développement. 
Il faut faire la police ...

**Comment by Pavell94000** [comment]
La seule différence entre les deux versions est le fait que le mathjax n'a pas de probleme de chargement sur pre-prod. On a du faire ca pour la présentation EIAH de la semaine derniere car on avait pas le temps de faire un deploiement.

**Comment by nimdanor** [comment]
OK,
tu viendras au premier salle 40 demain matin.

**Comment by nimdanor** [comment]
@Pavell94000  remarque les numéros de version sont identiques ...
ce qui n'aide pas (il faut peut être ajouter un niméro de versions dans un commentaire 
dans le base html.
