### ISSUE TITLE
un exo qui plante 

### ISSUE THREAD

**Issue by nimdanor** [PremierLangage/premierlangage#273]
ne fonctionne pas sur préprod problème de parsing du template ... 
/conceptexo/computerscience/python/concept/bool/boolcond.pl 

la version pl.u-pem.fr contourne le problème ...

**Comment by Pavell94000** [comment]
Je crois que c'est la sandbox qui démarrait, j'ai recu un mail
je viens de le tester il semble fonctionner

**Comment by Pavell94000** [comment]
J'ai rien dit, les variables d'affichent pas..

**Comment by Pavell94000** [comment]
Au final, c'est la facon d'importer le builder before qui empechait les variables de s'afficher, la bonne manière d'importer est:@ /builder/before.py [builder.py]

La syntaxe builder=@  /builder/before.py semble cassée
