### ISSUE TITLE
Bug 

### ISSUE THREAD

**Issue by nimdanor** [PremierLangage/premierlangage#275]
Failed to load 'Yggdrasil/conceptexo/ComputerScience/python/concept/function/func.pltp':
conceptexo/ComputerScience/python/concept/function/decomposition.pl at line 12 -- Library 'https' does not exists : 'https:/latex.codecogs.com/gif.latex?2*3^4*11*13^2'
2*3^4*11*13^2.

Strange error message et strange error ...

**Comment by Pavell94000** [comment]
Le bug provient du parser PL (ligne 84-87), il cherche des fichiers dans le filebrowser si il trouve un lien par la regex : SRC = r'(img.+?(?=src)src\s*=(?:\"|\')(?!\/filebrowser)(?P<src>[^\"|\']+)(?:\"|\'))'
Est ce que le bout de code sert a ctrl clic dans le filebrowser ?
La regex est surement pas bonne, elle trouve des liens qui ne devraient pas etre ctrl cliquable

**Comment by mciissee** [comment]
Ce code a déjà été remplacé par l’oper $= sur la branche tags

**Comment by qcoumes** [comment]
Can this issue be closed ? @mciissee

**Comment by mciissee** [comment]
yes
