### ISSUE TITLE
Syntaxe de liens extends

### ISSUE THREAD

**Issue by nimdanor** [PremierLangage/premierlangage#283]
IL faut que l'on change la syntaxe des extends pour qu'il soit plus compatible avec la syntaxe ctrl-click

     extends= /truc/mahcine 
nouvelle syntaxe 

      extends@ /truc/mahcine 

@mciissee c'st ce que l'on a dit ?

**Comment by mciissee** [comment]
Le ctrl click fonctionne déjà pour le mot clé entends donc je pense qu'il n'est pas nécessaire de changer la syntaxe et que cette issue peut être fermée
