### ISSUE TITLE
Déploiement 

### ISSUE THREAD

**Issue by nimdanor** [PremierLangage/premierlangage#285]
@Pavell94000 
@mciissee 
Salut pouvez vous organiser un déploiement des input tags sur la prod,
pour que l'on puisse l'utiliser pendant la semaine du 1 juillet dans le WimsAthon.

**Comment by Pavell94000** [comment]
Ce sera un déploiement de la 0.6.2 qui contient aussi le changement de template vers jinja2 et risque surement de casser des pl qui se servent des templates django (par exemple il n'y plus de load)
On déploie quand meme la 0.6.2, ou juste les input tags ?

**Comment by qcoumes** [comment]
Les tags ne sont pas encore complètement testés, on ne peut pas faire un déploiement sur la prod en 4 jours. Sur préprod au pire.

**Comment by nimdanor** [comment]
ok une version sur pl-test que je puisse commencer à écrire des exercices ...

**Comment by nimdanor** [comment]
des nouvelles du déploiement ?
