### ISSUE TITLE
Filebrowser freezing firefox when multiple subkeys are used

### ISSUE THREAD

**Issue by Pavell94000** [PremierLangage/premierlangage#287]
You can try to reproduce this bug on https://pl-test4.u-pem.fr/filebrowser .
In file lib/demo/static_add.pl try to add a line of the shape `azerty.azerty.azerty.azerty.azerty.azerty.azerty` and it will progressively slow down firefox until it completely freeze.
It seems to be an auto-completion problem with the editor.

**Comment by nimdanor** [comment]
I  don't know if this is important should be relayed to the original software.
