### ISSUE TITLE
Euh il est 9:09

### ISSUE THREAD

**Issue by nimdanor** [PremierLangage/premierlangage#290]
@Pavell94000 @qcoumes 

![Screenshot_2019-07-09 UPEM - PL](https://user-images.githubusercontent.com/10084549/60866695-541c2400-a229-11e9-93cf-49281e4af867.png)

**Comment by nimdanor** [comment]
mais on est sur préprod ...

**Comment by nborie** [comment]
Au fait, je voulais vous dire un truc !

**Comment by nborie** [comment]
Non non, rien !
