### ISSUE TITLE
20 characters are not enough for Course's label

### ISSUE THREAD

**Issue by qcoumes** [PremierLangage/premierlangage#303]
Course's label are currently limited to 20 chars, it's not enough as it seems Moodle can send way longer label (35+).

Something like 255 should be enough.

**Comment by ddoyen** [comment]
That's probably why I can't launch PL activities from some of my Moodle courses. Could it be fixed quickly ? I need to prepare a Moodle course with PL activities before september.

**Comment by qcoumes** [comment]
Yes, this is probably the cause. The fix will be include in the next release which is scheduled for the 10/09.

**Comment by ddoyen** [comment]
Ok thanks. In the meantime, I've managed to create a Moodle course with a name short enough.

**Comment by nimdanor** [comment]
What's the limit of moodle cours ? let's set the size to this limit if it's superior to 255.
Maybe you can go to 256 if there is no end of string char ?

**Comment by nimdanor** [comment]
Never mind 255 is the right size ;)
https://stackoverflow.com/questions/2340639/why-historically-do-people-use-255-not-256-for-database-field-magnitudes
