### ISSUE TITLE
Size of an Input component

### ISSUE THREAD

**Issue by ddoyen** [PremierLangage/premierlangage#305]
I can't change the size of an Input component. I've tried the code below.
~~~
@ /utils/sandboxio.py
grader  =@ /grader/evaluator.py
builder =@ /builder/before.py

extracss ==
<style>
c-input {
    width:10px;
    color: red;
}
</style>
==

component =: Input

before==
==

title==
Input Component
==

text==
==

form==
{{ component|component}}
==

evaluator==
grade = (100, component.value);
==
~~~

It does change the color but not the size.

**Comment by mciissee** [comment]
This is not a bug the only way you can customize components is to use the css properties of the ones that accepts it. As @nimdanor want this will prevent to provide a feedback in an exam mode.

In your case if you just want to set the dimension of any component you have to wrap it around a div and set a width|height for the div so the component will take 100% of the dimension of the parent.

**Comment by mciissee** [comment]
Example:
```
<div style="width: 100px"></div>
```
or 
```
<div class="my class"></div>
```

**Comment by mciissee** [comment]
Internally any component as a css selector in the form .NAME-component where NAME the the name of the component (input -> .input-component,  math-input -> math-input-component...) You can also use this selector from css to change the style of a component but if we decide to change the naming convention in the future of the name of the component your code will not work anymore.

```
@ /utils/sandboxio.py
grader  =@ /grader/evaluator.py
builder =@ /builder/before.py

extracss ==
<style>
/* will work but not recommended since the name can change in the future */
.input-component {
    width:10px;
    color: red;
}
</style>
==

component =: Input

before==
==

title==
Input Component
==

text==
==

form==
{{ component|component}}
==

evaluator==
grade = (100, component.value);
==
```

**Comment by mciissee** [comment]
Is this can be closed @ddoyen?
