### ISSUE TITLE
MathDrawer component

### ISSUE THREAD

**Issue by ddoyen** [PremierLangage/premierlangage#306]
I'd like to enforce the aspect ratio of the JSXGraph panel in the MathDrawer component.

Without component, the code below worked.

~~~
<div id="jxgbox" class="jxgbox" style="max-width:300px;width:80vw;max-height:300px;height:80vw;margin: 0 auto;">
</div>
~~~

How can I get the same behavior with the component ? I tried to encapsulate the component in a div but I end up with a vertical overflow.

**Comment by ddoyen** [comment]
I have another question related to the MathDrawer component.

In an exercise with JSXGraph, I used JS functions to add a specific behavior (a click on the panel moves the point to the click location). See JS code below.

~~~
<script>
var board = JXG.JSXGraph.initBoard('jxgbox',{boundingbox:[-6,6,6,-6],axis:true,grid:true,showNavigation:false});
board.create('grid',[],{gridX:1,gridY:1});
board.create('axis',[[0,0],[1,0]],{name:'Re',withLabel:true,label:{position:'urt',offset:[-5,10]},ticks:{visible: false}});
board.create('axis',[[0,0],[0,1]],{name:'Im',withLabel:true,label:{position:'urt',offset:[10,0]},ticks:{visible: false}});
var M = board.create('point',[0,0],{size:2,name:'M',color:'red'});

function getMouseCoords(e) {
    var cPos = board.getCoordsTopLeftCorner(e);
    var absPos = JXG.getPosition(e);
    var dx = absPos[0]-cPos[0];
    var dy = absPos[1]-cPos[1];
    return new JXG.Coords(JXG.COORDS_BY_SCREEN, [dx, dy], board);
}

function down(e) {
    coords = getMouseCoords(e);
    M.setPosition(JXG.COORDS_BY_USER,[coords.usrCoords[1], coords.usrCoords[2]]);
}

board.on('down',down)
</script>
~~~

How do I adapt these functions to the new component syntax ?

**Comment by mciissee** [comment]
For the first question as I explained for the issue #305 each component can be globally customized using a css class in the form **.NAME_component** where **NAME** is the name of the component in lower case and spaces and non alphabetic characters replaced by **-**. In the case of Math Drawer the class is **.math-drawer-component**.

For the second question JSX object 'board' is created by the component itself. There is an example of usage of the component in the doc showing how to access the board object in JS and add extra behaviors.

The following example integrates the answer of your questions.

```
@ /utils/sandboxio.py
grader  =@ /grader/evaluator.py
builder =@ /builder/before.py

drawer =: MathDrawer
before==
==

title==
Math Drawer Component
==

text==
==

form==
{{ drawer|component }}
==

extracss==
<style>
.math-drawer-component {
    max-width:300px;
    width:80vw;
    max-height:300px;
    height:80vw;
    margin: 0 auto;
}
</style>
==
extrajs==
<script>
    /**
    * This function is called by the component once the page is loaded
    * board argument is an instance of JSX Graph board.
    **/
    function onMathDrawerReady(component) {
        const board = component.board;
        board.create('grid',[],{gridX:1,gridY:1});
        board.create('axis',[[0,0],[1,0]],{name:'Re',withLabel:true,label:{position:'urt',offset:[-5,10]},ticks:{visible: false}});
        board.create('axis',[[0,0],[0,1]],{name:'Im',withLabel:true,label:{position:'urt',offset:[10,0]},ticks:{visible: false}});
        var M = board.create('point',[0,0],{size:2,name:'M',color:'red'});

        function getMouseCoords(e) {
            var cPos = board.getCoordsTopLeftCorner(e);
            var absPos = JXG.getPosition(e);
            var dx = absPos[0]-cPos[0];
            var dy = absPos[1]-cPos[1];
            return new JXG.Coords(JXG.COORDS_BY_SCREEN, [dx, dy], board);
        }

        function down(e) {
            coords = getMouseCoords(e);
            M.setPosition(JXG.COORDS_BY_USER,[coords.usrCoords[1], coords.usrCoords[2]]);
        }
        board.on('down',down)
    }
</script>
==

evaluator==
grade = (100, 'Bonne réponse');
==
```

**Comment by mciissee** [comment]
I have another little remarks. You should avoid to use var keyword when working with JS.
You should use the keyword **const** for variables that are affected only one time and **let** for local variables.

**Comment by ddoyen** [comment]
Thanks. I didn't think to simply use nested functions. Now it works.

But, I can't get the style that I want with the component. I'm probably missing something in the default attributes of the component (By the way, where can I find all the source files related to the components ? I can't find them on GitHub). 

Here is the standard behavior with the component. When the window is too small, it resizes the JSXGraph panel without keeping the aspect ratio and the circle becomes an ellipse.

https://pl.u-pem.fr/filebrowser/option?name=test_pl&path=Yggdrasil/Mathematics/exercises/jsxgraph/test0.pl

Here is something that works (without the component). It resizes the JSXGraph panel while keeping the aspect ratio.

https://pl.u-pem.fr/filebrowser/option?name=test_pl&path=Yggdrasil/Mathematics/exercises/jsxgraph/test1.pl

Here is an attempt to change the component CSS. It overflows.

https://pl.u-pem.fr/filebrowser/option?name=test_pl&path=Yggdrasil/Mathematics/exercises/jsxgraph/test2.pl

**Comment by mciissee** [comment]
This is a bug with the component you should target the css class **.jxgbox** instead of **.math-drawer-component**. I will keep the both classes in the next release so it will not break your code.

You can also target math drawer components using id selector **board_N** where **N** is a number between [1, infinity] corresponding to the declaring order of the component.

I modified the file test2 it should work now.

Components source code is not currently exposed on Github.

**Comment by ddoyen** [comment]
Thanks, it works. I carry on with a new series of Issues. :-)

1. An issue similar to #302. I can't change the attributes of a MathDrawer component.

~~~
drawer.attributes %=
{
    "boundingbox": [
      -6,
      6,
      6,
      -6
    ],
    "showNavigation": false
  }
==
~~~

The attributes are modified in the debug display but the JSXGraph panel is not modified accordingly.

2. Object persistence in the board & additional script for correction

After the answer is validated, the board is recreated with the initial parameters, erasing the modifications made by the student (most often, point locations).

I'd like to keep the modifications made by the students after the validation.

Also, I'd like to be able to run an additional script to display a correction in the JSXGraph panel.

**Comment by mciissee** [comment]
1. For this problem I need to know the version of your browser. Is the problem occurs only with this browser? I need also to see and test the code you are trying.

2. The board is recreated because this is the current behavior of PL. When you submit the answer the page is reloaded after the grade. Since the component properties are saved after the grade so should see the modification of the student after the grade (the position of the points) You can activate the debug mode to check if the points are saved after the grade. If not this is a bug.

**Comment by ddoyen** [comment]
Here is the code (tested with Firefox 68.0.1 and Chromium 76.0.3809.87).

https://pl.u-pem.fr/filebrowser/option?name=test_pl&path=Yggdrasil/Mathematics/exercises/testcomp/stylejsxgraph.pl

~~~
@ /utils/sandboxio.py
grader  =@ /grader/evaluator.py
builder =@ /builder/before.py

drawer =: MathDrawer

drawer.attributes %=
{
    "boundingbox": [
      -6,
      6,
      6,
      -6
    ],
    "showNavigation": false
  }
==

drawer.debug = True

before==
==

title==
Math Drawer Component
==

text==
==

form==
{{ drawer|component }}
==

extrajs==
<script>
    function onMathDrawerReady(component) {
        const board = component.board;
    }
</script>
==

evaluator==
grade = (100, 'Bonne réponse');
==
~~~

**Comment by mciissee** [comment]
Il will fix **1)** for the next release for the second issue we need to talk because I don't know exactly what properties this component should expose. In any case the current behavior of PL is to reload the entire page after each submission, the components state is initialized after each page reload with properties modified in the grader.

**Comment by mciissee** [comment]
Can you repost  this issue and all the ornées related to components in component  repo @ddoyen? 

I will close the component issues from this repo

**Comment by mciissee** [comment]
Moved to components repository so this one will be closed
