### ISSUE TITLE
browser back doesn't work in componant documentation

### ISSUE THREAD

**Issue by nimdanor** [PremierLangage/premierlangage#308]
The URL in the url bar changes but the content stay the same when i use the back button of the browser in this case chrome.
Same problem with firefox.

**Comment by mciissee** [comment]
This is the default behavior of a  single page application since premier langage routing is handled by Django, routing in components page is disabled.

**Comment by nimdanor** [comment]
OK.
But why did you shoose a single page application for the documentation ?

**Comment by mciissee** [comment]
Since the components are written in Angular an Angular is a single page application framework there is no reason to write the doc in classic HTML. Write the doc in html will require to write a single html file for each component so this is not possible and maintainable.

**Comment by mciissee** [comment]
The doc also contains interactive examples that cannot be written in HTML

**Comment by mciissee** [comment]
Is this can be closed @nimdanor?
