### ISSUE TITLE
PLTP activities can be reloaded by anyone

### ISSUE THREAD

**Issue by ddoyen** [PremierLangage/premierlangage#315]
Currently, anyone can reload the activity number XX with any PLTP file. It's a bit risky since we are going to use PL seriously this semester. A mistake in the number when reloading an activity and someone else's activity is totally replaced (what about student data)...

**Comment by nimdanor** [comment]
Yes this should be adressed.
@qcoumes can we associate a "moodleid" from LTI to a activity in PL to check if this is right ?

**Comment by Pavell94000** [comment]
With the new activities, you can't reload an activity where you are not a teacher
