### ISSUE TITLE
[BUG] Truncated sidebar in PLTP activities

### ISSUE THREAD

**Issue by ddoyen** [PremierLangage/premierlangage#318]
## Description

There is a side bar in PLTP activities to navigate through the exercise list. In one of my PLTP activity (containing 12 exercises), the exercise list is truncated in the sidebar end I can't reach the last exercise. Resizing the window doesn't change that. Even when there is the scroll bar in the side bar, I can't reach the last exercise.

## Expected behavior
One should be able to reach all the exercises in the side bar, possibly with a scroll bar.

## How to reproduce

Try https://pl.u-pem.fr/playexo/activity/162/ 

There are 12 exercises in the activity.

## Config
- Ubuntu 16.04 (64 bits)
- Firefox 68.0.2
- Chromium 76.0.3809.100

**Comment by qcoumes** [comment]
Fix by 0.6.3
