### ISSUE TITLE
How to edit name, title and introduction in PLTP activities after creation ?

### ISSUE THREAD

**Issue by ddoyen** [PremierLangage/premierlangage#333]
When I reload an already existing PLTP activity, the exercise list is updated. But the name, title and introduction of the PLTP remain what they were at the first load.

Is there a way to edit these values ?

**Comment by qcoumes** [comment]
Title and introduction of the PLTP should normally be updated when reloading a PLTP.

**Comment by ddoyen** [comment]
It's quite annoying. I'm stuck with a sheet with a wrong title and information in a course. I can't even delete it.

There must be some way to change that manually.

**Comment by qcoumes** [comment]
I opened an issue asking for the possibility to delete an Activity.

For now, I can either edit your activity or delete it if you give me its ID.

**Comment by ddoyen** [comment]
Ok, thanks. Then, could you please delete activity number 1.

**Comment by Pavell94000** [comment]
Reload is fixed with the last version
