### ISSUE TITLE
[BUG] Problems with the editor

### ISSUE THREAD

**Issue by plgitlogin** [PremierLangage/premierlangage#334]
The editor on http://PL.u-pem.fr as stranges behaviors.
1) cmd+click doesn't work any more
2) the moose wheel doesn't scroll the text in the editor 
3) the git menu as vanished (THIS is nimdanor's Falt) should be around
We need it for the moment. Or is it only visible for ADMINS ?

**Comment by qcoumes** [comment]
1 & 2 are known bug.

For 3, the git menu is only visible by admins.

**Comment by niotie** [comment]
> the moose wheel doesn't scroll the text in the editor

I'm trying to imagine what a moose wheel looks like...

**Comment by nimdanor** [comment]
you move the desk around it ;)
