### ISSUE TITLE
[ENHANCEMENT] Allow the deletion of Activity

### ISSUE THREAD

**Issue by qcoumes** [PremierLangage/premierlangage#336]
Teacher should be able to delete activities from their Course.

**Comment by ddoyen** [comment]
I see that this feature has been added.

However, I suggest to display an alert message and ask a confirmation from the user before performing this action.

**Comment by Pavell94000** [comment]
When using this feature, the activity is not really delete, it is just removed from the course. You still can add it to the same course with the same id

**Comment by ddoyen** [comment]
Ok.
