### ISSUE TITLE
[BUG] loosing the editor content in an exercice

### ISSUE THREAD

**Issue by nimdanor** [PremierLangage/premierlangage#337]
## Description
When using 
form=@ /form/text_editor.html
in a programming exercice i loose the content of the editor 

## Expected behavior
the editor should keep the content entered by the user.

## How to reproduce
https://pl.u-pem.fr/filebrowser/option?name=test_pl&path=Yggdrasil/ComputerScience/python/AP1-1920/drafts/Theme1-bases-imperatif/interchanger_deux_variables.pl
enter any answer 

## Config
Firefox 
chrome 

je pense que c'est partout

**Comment by mciissee** [comment]
The referenced file is deleted.

**Comment by nimdanor** [comment]
the content of the student-editor in nearly all exercices is lost after validate.
https://pl.u-pem.fr/filebrowser/option?name=test_pl&path=Yggdrasil/ComputerScience/python/concept/variable/variable001.pl
https://pl.u-pem.fr/filebrowser/option?name=test_pl&path=Yggdrasil/ComputerScience/python/concept/variable/variable002.pl
https://pl.u-pem.fr/filebrowser/option?name=test_pl&path=Yggdrasil/ComputerScience/python/concept/variable/variable003.pl

**Comment by mciissee** [comment]
I updated the `text_editor.html` template replacing this template to use CodeEditor component will require a lot of effort since the current text_editor is used in a lot of places. Each teacher with a template using this editor should update the template to use the CodeEditor if he want.

**Comment by nimdanor** [comment]
Can you give a simple process to transform a exercice template from old to new ?
