### ISSUE TITLE
[ENHANCEMENT] MatchList component improvement

### ISSUE THREAD

**Issue by nborie** [PremierLangage/premierlangage#342]
Very minor suggestions for MatchList after the following test...

https://pl.u-pem.fr/filebrowser/option?name=test_pl&path=Yggdrasil/ComputerScience/C/exercices/function/prototypes.pl

* Please add more vertical space after displaying the exercise text. Currently the top proposition is too close to the text.

* Currently, it seems to me that the text feedback is not provided. Since a lot of people will use it as I did (copy paste then customization...), it could be fine that the example in the doc provide a displayed textual feedback.

* Colors work fine during correction. Perhaps links could have more thickness ? (This stays just a suggestion but edges seems to me very fine...).

**Comment by mciissee** [comment]
> Please add more vertical space after displaying the exercise text. Currently the top proposition is too close to the text.

extending the styling of an exercise is possible but not currently documented unfortunately.
Each section of the exercise (title, instructions, feedback, actions...) has a css class selector which can be used from css to customize it. for example the class of the feedback area is **exercise__feedback** in the example below I use the selector inside `extracss== `key to add a bottom margin to the **instructions** and **feedback** areas. (the extracss key is inserted into the HTML by the server).
I will add margin to the default template for the next release.

> Currently, it seems to me that the text feedback is not provided. Since a lot of people will use it as I did (copy paste then customization...), it could be fine that the example in the doc provide a displayed textual feedback.

By textual feedback you means the one created by a teacher with `grade = (score, feedback)` ? 

> Colors work fine during correction. Perhaps links could have more thickness ? (This stays just a suggestion but edges seems to me very fine...).

As for the exercise template page each component as a unique css selector (the same name as the component in snake-case format with -component suffix. example: MatchList -> .match-list-component). The customization of the component should be done by the teacher inside extracss or form keys like I did in the example below. 

The feature requests and issues related to components should be done at [https://github.com/PremierLangage/components/issues](https://github.com/PremierLangage/components/issues)

I modified your exercise with the remarks by adding the code below at [https://pl.u-pem.fr/filebrowser/option?name=test_pl&path=Yggdrasil/ComputerScience/C/exercices/function/prototypes.pl](https://pl.u-pem.fr/filebrowser/option?name=test_pl&path=Yggdrasil/ComputerScience/C/exercices/function/prototypes.pl)

```
extracss==
<style>
.exercise__instructions, .exercise__feedback {
    margin-bottom: 16px;
}

.match-list-component svg path {
    stroke-width: 4px;
}
</style>
==
```

**Comment by nborie** [comment]
> for example the class of the feedback area is **exercise__feedback** in the example below I use the selector inside `extracss== `key to add a bottom margin to the **instructions** and **feedback** areas. (the extracss key is inserted into the HTML by the server).
> I will add margin to the default template for the next release.

Fair enough.  

> By textual feedback you means the one created by a teacher with `grade = (score, feedback)` ?

Yeap, I see this feedback now..

> The feature requests and issues related to components should be done at https://github.com/PremierLangage/components/issues

Oki thanks. So this can be can closed... 
If I have more to ask, I will do it on the right place.
