### ISSUE TITLE
[BUG] invalide activity comportement

### ISSUE THREAD

**Issue by nimdanor** [PremierLangage/premierlangage#345]
## Description
the "success" of an exercice is false.

## howto reproduce 
in the AP1 course/pltp on Variables and all.
https://pl.u-pem.fr/activity/play/45/
place yourself on exercice "lecture d'un caractère" 
make a wrong answer 
place yourself on the following exercice "manipulation de nombres"
and TADA !!!
your exercice  "lecture d'un caractère" is GREEN

## solution
I think the bug is in the activity ?

## Config
On upem's computers with firefox ESR

**Comment by Pavell94000** [comment]
It is probably in the grader, i tried to answer with "TEST" and my grade is 100.
You can check my answer here : https://pl.u-pem.fr/admin/playexo/answer/43821/change/
The only thing that makes a PL green in the activity navigation is the grade
