### ISSUE TITLE
[BUG]  editeur visible pour un étudiant 

### ISSUE THREAD

**Issue by nimdanor** [PremierLangage/premierlangage#352]
## Description
Connection depuis elearning avec le compte EssoxLucius1 
ce compte est connecté comme etudiant sur le cour premerilangage 
et pourtant que je me connect sur pl j'ai accès a Editeur ?

## Normalement
Cela ne devrai pas être possible. 
On est prof /etudiant par corus sur moodle et cela devrai être pareil sur PL
quand on accède en tant qu'étudiant on ne doit pas voir l'éditeur.

Je pensai que cette erreur était connue et corrigé ??

**Comment by qcoumes** [comment]
Non, cela n'a jamais été corrigé, le système de rôle actuel ne le permet pas.

**Comment by Pavell94000** [comment]
A partir du moment ou le compte s'est connecté une fois en enseignant, l'éditeur est visible pour tout le monde

**Comment by nimdanor** [comment]
le role est définitif a la première connection ?

**Comment by nimdanor** [comment]
on peu retirer le role à la main dans administration ?

**Comment by Pavell94000** [comment]
Oui je viens de le faire pour elucius, il faut lui remettre le role Student dans la section Profile

**Comment by nimdanor** [comment]
Ok merci

Le mer. 9 oct. 2019 à 22:31, Christophe Callé <notifications@github.com> a
écrit :
