### ISSUE TITLE
[ENHANCEMENT] Activites should be ordered inside courses. One could re-order them.

### ISSUE THREAD

**Issue by nborie** [PremierLangage/premierlangage#356]
I did begin to spread some PLTP of C to the L3...

The add mechanism is just perfect (an integer : you should call it the activities descriptor). After adding a sixth PLTP, the other has been mixed... But I did try to order them from simplest to hardest and it is no more the case now.

This is not urgent. In a perfect world, teacher can re-order activities inside a course. Like moodle, a kind of drap'n'drop over an ordered content inside courses/activities.

**Comment by Pavell94000** [comment]
It's now possible, no drag & drop though

**Comment by nborie** [comment]
The two arrows up/down did allows me to reorder the pltp inside a course. It is ok for me.

**Comment by nborie** [comment]
This work has been done by Pavell and the feature is still working well in production.
