### ISSUE TITLE
[ENHANCEMENT] New Parser

### ISSUE THREAD

**Issue by mciissee** [PremierLangage/premierlangage#380]
**Describe the solution you'd like**
After a discussion with @nimdanor yesterday, we agreed that we should update the current parser of a PL exercise to a new version which support typed variables. I modified a little the proposition.

The parser will support the following types: string, int, float, list, dict, url.

Example:

```python
myint = 10
myfloat = 1.0 
mystr1 = lorem ipsum
myexplicitestr: string = 10
mylist = [10, 20, 30]
myexplictlist = [10, 20, 30]

# the parser should warn the teacher that the variable seems to be an array
# and that he should fix the syntax or explicitly specify the type if it's a string.
myambiguouslist = [10, 20, 30


mydict = { "key": "value" }
# same remarks as for myambiguouslist
myambiguousdict = { "key:" value


myexplitdictstr: string = { "key": "value" }
myexplicitdict: dict = { "key": "value" }

myexplicitdict2: dict ==
{ "key": "value" }
==

# replace the =$ operator
myurl: url = /lib/folder/file.png

```

The behavior of the parser is the following when it find the declaration of a variable it will try to find the type from the value at the right of the = operator (int and float types are simple) but sometimes we want to declare a string as a number so this is where the explicit type specifier comes. To explicitly define the type of a variable the following syntax is used:

`name: type = value`

In this way the teacher removes ambiguities in the situations where the parser cannot guess the type.

With this new parser pl will support only 6 operators:

- `=` with the variants (`+=, -=, ==`). `+` and `-` should be removed because they introduce ambiguities like in the following code.
```
mystr = lorem
mystr + ipsum # this is not explicit

mystr2 = lorem
mystr2 += ipsum # the usage of the = operator remove the ambiguity here.
```

The parser should know that if the value after += is on the same line, the == operator is not necessary in this way we can remove + and - operators and keep only =, +=, -= (and == at the end in the case of a multiline value.

The + and - operator should be applied differently depending on the type of the variable (increment, decrement for int and float) (concat list, or sub list in the case of list types) (concat dicts in the case of + operator for dict types)

- `@` to put a file on the sandbox

- `=@` to affect the content of a file to a variable

- `@ file [alias]` the import alias operator

- `=:` to create a component 

- the pltp decorator operator to decorate the a pl inside a pltp (this last one is to be discussed)
```
({
 "title": "value",
 "text": "value"
})
@ exercise.pl
```

**Additional context**
**The parser should be released with a script that will updated deprecated codes during the release.** 

What do you thing about this @nimdanor ?

**Comment by mciissee** [comment]
The is also the boolean type (True or False)

**Comment by ddoyen** [comment]
Two remarks.

1. For one-line affectation of strings, why not simply use quotes ? It would make things simpler : no need of an additional syntax for the operator `=` (except maybe for url). Besides, it would be more consistent with other languages and clearer for newcomers. The extra effort in typing quotes seems to me a small price to pay.

2. I don't see which data type, besides strings, needs a multiline affectation operator. If so, the operator `==` could be reserved to multiline strings (no need of quotes in this case).

**Comment by mciissee** [comment]
> For one-line affectation of strings, why not simply use quotes ? It would make things simpler : no need of an additional syntax for the operator = (except maybe for url). Besides, it would be more consistent with other languages and clearer for newcomers. The extra effort in typing quotes seems to me a small price to pay.

We cannot ensures backward compatibility by using quotes


> I don't see which data type, besides strings, needs a multiline affectation operator. If so, the operator == could be reserved to multiline strings (no need of quotes in this case).

list and dict types could be declared in multiline

**Comment by ddoyen** [comment]
1. The update does not seem untractable.

~~~
var1 = blabla

var2 % 2.3
~~~
would be updated


2. But there is no ambiguity for multiline dict or list, is there ? In Python, there is no specific operator for example.

**Comment by niotie** [comment]
As suggested by @mciissee, here is another idea for the future parser.

In some use cases, it would be nice to be able to build a path dynamically depending on the context, and use the obtained value at the right-hand side of a '=@' operator (for instance). Something like this :

```
my_text_file = root + '/enonce.md'
text @= my_text_file
```

I guess the problem is that the parser can't distinguish a variable name from a literal string.

**Comment by niotie** [comment]
Also, if I want to be able to use this in interesting ways, I need some way to do conditions :

```
if root:
    my_text_file = root + '/enonce.md'
    text @= my_text_file
else:
    text = Aucun énoncé n'a été défini pour cet exercice
```

**Comment by nimdanor** [comment]
je continue a aimer le début de cette issue.

Rappel il n'y pas vraiment de syntaxe spécifique à PL
Un PL c'est un dictionnaire clef valeurs
en suite les fichiers builder.py et grader.py interprètent ce dictionnaire.
Puis l'application playexo utilise certaines balises pour faire de  l'affichage
actuellement: text, title, form
mais cela pourrai dans l'avenir changer aussi en utilisant une balise template_html (ou équivalente) qui
permet de spécifier quelles balises sont utilisées par l'affichage.
Enfin certaines balises sont "filtrées" dans le template_html actuel (et pas toute de la même façon).


Donc les objectifs de la version 1:
1) Conserver un comportement simple pour le comportement par défaut. Donc les filtres markdown et latex en général pour les variables qui s'affichent.
Attention dans l'exemple d'Antoine il propose des variables filtré dans d'autres variables, c'est un des souci de passer plusieurs fois le même filtre \\\*, je pense qu'il faut mieux avoir un filtre final dans le template [@mc @qcoumes vote avis].
2) Permettre de faire de la vérification syntaxique du contenue des balise et donc proposer du typage.
Actuellement nous étions parti sur :
nomdelabalise: type de la balise = ou == 
Ce qui permet de typer les balises simples ou multi-lignes.
-----------------
Ajoutons la problématique des filtres, ce qui est une excellente initiative :)
Je propose simplement de porsuivre avec la même syntaxe que les types (avant le caractère d'affectation):
balise:type|filtre=
balise:type|filtre==
et dans le cas de filtre multiples :
balise:type|filtre|filtre2|...|filtreN==
On garde le coté droit de == pour des indication de mise en page dans l'éditeur.

**Comment by nimdanor** [comment]
Je repette le typage est nécessaire comme en javascript ;)
Le typage explicite permet le controle dans les fichiers "d'utilisation" donc c'est une syntaxe nécessaire. 

En suite pour le code c'est pas agréable d'avoir a quoté du code.

Allez donc quoté:
```
def f(été):
    """
    il était "affolé" de la complexité
    """ 
    return "toto" + 'titi' + "aujourd'hui" + ' 3" et 4° '+ ''' rien de rien '''
```

**Comment by qcoumes** [comment]
> Allez donc quoté:
> 
> ```
> def f(été):
>     """
>     il était "affolé" de la complexité
>     """ 
>     return "toto" + 'titi' + "aujourd'hui" + ' 3" et 4° '+ ''' rien de rien '''
> ```

Avec une triple quote python cela donne juste
```
f='''
def f(été):
    """
    il était "affolé" de la complexité
    """ 
    return "tototitiaujourd'hui  3" et 4°  rien de rien "
'''
```

**Comment by nimdanor** [comment]
Donc tu ne peux pas copier coller un code directement tu est obligé de l'éditer 
pour corriger les problèmes donc pas terrible NON ?
Avec le type code pas de problèmes.

**Comment by qcoumes** [comment]
J'attends de voir un vrai exemple au lieu d'un example artificiel. Je n'ai encore jamais vue en 6 ans de fac une chaine avec des triples apostrophe (et le saint graal du triple apostrophe + triple guillemet).

Quitte à être de mauvaise fois, je peux faire la même chose :
```python
def f(été):
    """
    il était "affolé" de la complexité
    """ 
    return """tototitiaujourd'hui  3" et 4°  rien de rien
==
avec des double égales"""
```

J'attends de voir comment copier directement ce code sans le modifier avec la syntaxe actuelle

**Comment by nimdanor** [comment]
Peut être en effet que python est magique mais j'ai plein d'expériences délicates avec la déspécialisation de caractères .

**Comment by ddoyen** [comment]
Je mets par écrit notre discussion de cette semaine avec @nimdanor et @mciissee

La syntaxe des expressions JSON est légèrement différente des expressions Python correspondantes :
* true/false vs True/False
* null vs None
* simple quotes non acceptées en JSON pour délimiter les chaînes

Or, en pratique, on est amené à jongler avec les deux syntaxes pour les clés (selon qu'on les définit dans le source PL ou dans un script Python), ce qui est perturbant, surtout pour les néophytes.

Je propose donc que le parser PL soit capable d'interpréter la valeur qui est à droite de l'opérateur `=`, que ce soit du JSON ou que ce soit une expression Python composée de int/float/str/bool/None/list/dict.

1. D'abord on essaie d'interpréter la chaîne qui est à droite de l'opérateur `=` comme du JSON.
2. Si l'on n'y arrive pas, on essaie de l'intepréter comme du Python (Note: la commande `ast.literal_eval` fait ça plus spécifiquement que `eval`).
3. Si l'on n'y arrive toujours pas, on la considère comme une chaîne.

Exemples :
```
# key1 sera lu comme false
key1 = False

# key2 sera lu comme null
key2 = None

# key3 sera lu comme la chaîne "toto"
key3 = 'toto'

# key4 sera lu comme la chaîne toto
key4 = toto
```

**Comment by nimdanor** [comment]
Je ne pense pas que la "double" syntaxe soit une bonne idée.
J'affirme qu'il faut abandonner le syntaxe JSON pour les clefs dans le fichiers format pl* et ne garder qu'une syntaxe python plus simple car commune. Ce qui permet en particulier des déplacer du code d'un script à une clef sans changer de syntaxe.
Ainsi : 
```
key= (5, 6)
# ou 
key=[6, 5] 
```
produit une liste (et pas un tuple et une liste) de deux entiers car dans tout les cas comme le fait remarquer David nous sauvegardons l'information sous forme de JSON. 
Mais si des développeurs souhaite avoir une version pickle c'est possible il suffit d'écrire une version  des deux fichiers builder.py et grader.py permettant de sauvegarder en pickle.
En effet dans la version platon l'environnement reste sur la sandbox et donc ne fait pas d'aller retours  sur le réseau et n'est donc plus nécessaire d'utiliser JSON (ce qui nous a bien simplifier les choses jusqu'ici).

Ansi : 
si l'on à la clef 
```
mondico=[ "clef1": 55,\
     "clef2": "une valeur", ]
```
Elle peut être déplacé dans le builder before : 
```

before==
import module
mondico=[ "clef1": 55,\
     "clef2": "une valeur", ]

print(mondico)
==
```

**Comment by nimdanor** [comment]
Enfin dans le cas ou le parser échoue a identifier un littéral nous supposerons que c'est une chaine sans guillemets.

Une option de compilation peut afficher ou pas un warning dans ce cas la.

**Comment by ddoyen** [comment]
Personnellement, pas d'objection à basculer sur une syntaxe 100% Python.
