### ISSUE TITLE
[BUG] LTI links from moodle to activities : j'ai tout recassé !

### ISSUE THREAD

**Issue by nborie** [PremierLangage/premierlangage#381]
* Hé bien j'ai rajouté un PLTP sur le cours Programmation C (2019 TC) : C'est l'activité 177

* J'ai changé le lien sur le moodle (le lien tout en bas de la matière) pour 
https://pl.u-pem.fr/activity/play/177/  (C'est PL qui m'a dit que ce lien était bien)

* J'ai cliqué sur le lien pour voir s'il marche

* Ça m'a rajouté des cours pour lesquels je ne devrait pas avoir de droit : Prérentrée, Méthodologie des mathématiques et TestCourse

* Bon, il y a toujours pas de documentation (j'ai cherché un peu quand même) expliquant comment placer un lien depuis moodle vers PL. J'ai tenté le même truc que sur Programmation C avancé (le lien marche sur ce cours)... Et bien là paf, ça casse tout... Je ne vois pas ce que je fais de mal.

Bon courage !

**Comment by Pavell94000** [comment]
Au moins on a reçu des mails avec des logs un peu détaillé cette fois !
J'essaie de décortiquer ça au plus vite

**Comment by nborie** [comment]
This is too late and too far to dealt more with that...

Let us continue the monitoring on the current version of PLaTon if something similar reappear.
