### ISSUE TITLE
[ENHANCEMENT] on the web site of Plato, is the button "download" is necessary on the demo exercise ?

### ISSUE THREAD

**Issue by ochampal** [PremierLangage/premierlangage#396]
I don't see the interesting point with downloading the code of the demo exercise ont the web site of PL.
I think it's not a good idea for a demo.
Maybe change the name of the button in order to explain "how it works" but just "Download" i think it's not enough.

**Comment by nimdanor** [comment]
Il faut éliminer le bouton télécharger l'environnement dans la version démo des exercices.

@Pavell94000 ou @mciissee le quel de vous deux peut s'en occuper.

**Comment by nborie** [comment]
Hello, could this very minor enhancement enter the 0.7.5 ?

It's seems to me that disable a buton would not be so much tricky (a 5 lines patch no ?) and that the 0.7.5 could be a nice moment to close this ticket... If there is a tchnical blocker issue to disable this buton, @Pavell94000 (last playexo dev leader IIRC...) should now the problem.
