### ISSUE TITLE
[ENHANCEMENT] Official html syntax highlighter playexo-friendly

### ISSUE THREAD

**Issue by nborie** [PremierLangage/premierlangage#398]
I often need to include source code inside my exercises. I sometimes need to include teminal/shell code, C code or Python code. Until now, I deal with the html/css manually. And all my production are horrible. I did try some highlighter as triple-back-quote{#mycode .C} bla bla bla triple-back-quote but It didn't work...

Is there a feature, included in PLaTon, playexo-friendly, which allows to automatically set a nice coloration of source codes form general langages ? (like the code editor do but not inside a code form but inside a static html div...)

For example in https://pl.u-pem.fr/filebrowser/demo/12391/ I try to use an horrible mix of &lt;code&gt;  &lt;pre&gt; and some css badly writen...

If not, I will be very happy if one could add a reasonable html syntax highlighter in playexo.

**Comment by nimdanor** [comment]
Un composant editeur en mode readonly ?

**Comment by nborie** [comment]
Ok, this has been dealt with by Mcisse with a new component : https://github.com/PremierLangage/platon-front/issues/57 allowing to include highlighted code inside pl files.
