### ISSUE TITLE
[ENHANCEMENT] Enable the student summary course dasboard for Student

### ISSUE THREAD

**Issue by nborie** [PremierLangage/premierlangage#415]
We have a very nice view (and very fastly generated....) of a student summary for a whole course activity...

view at URL --> https://pl.u-pem.fr/activity/dashboard/<id_course>/?studentid=<id_student>

Please, just allow the student to show this !!! A nice boutton could be the "tableau de bord" up of the index.html template of course activity... Currently this button appears only you are teacher or admin, please enable this button for student for them to show their own marks.

The only check to perform is control that the student can see only its marks and no marks of other student...

DR try some experimentation on this pull request : https://github.com/PremierLangage/premierlangage/pull/413

The following screenshot display the kind of view which is very RGPD friendly...

![view_to_enable](https://user-images.githubusercontent.com/6042616/94454380-18fd6c00-01b2-11eb-8064-c5d10ea2b2e4.png)

**Comment by nimdanor** [comment]
![image](https://user-images.githubusercontent.com/10084549/94523878-20fcf080-0232-11eb-8750-f6b946668f30.png)
