### ISSUE TITLE
[BUG] Files in PL are parsed and read in a strange way

### ISSUE THREAD

**Issue by fwjmath** [PremierLangage/premierlangage#434]
## Description
When we design exercices for reading files using Python on PL, the files read are not exactly what we wanted. It is related to #433 probably. It should be the same bug, but since I don't know the internal working of PL, please take it with a grain of salt.

## How to reproduce
1. Go to the exercise in Yggdrasil/ComputerScience/python/AP1-2021/Chapitre_6_itérables/~matrix-file-2021.pl
2. Test the sample solution (under the tag "samplesol") on your own machine with the files mat*.txt in Yggdrasil/ComputerScience/python/AP1-2021/Chapitre_6_itérables/testcase. Please make sure to remove the extra empty line mentioned in #433 .
3. Test the same exercise again, but on PL using preview.

## Expected behavior
The function should work and produces a list of list without problem in both cases.

## Actual behavior
The function works correctly with Python3 on a local machine, but not on PL. After a precise inspection, we notice that on the empty file test case, the extra empty line ruins the number of lines we read.

## Config
Xubuntu, Python 3.8.5, Firefox

**Comment by nimdanor** [comment]
I think this is closed the print in the code is replaced by a write ;)
