### ISSUE TITLE
Copy link button

### ISSUE THREAD

**Issue by plgitlogin** [PremierLangage/premierlangage#56]
A nice enhancement is the possibility to have a button in the file browser interface that permit to copy the link to the file (in the copy buffer) so has to paste it in a pl or pltp file.

**Comment by qcoumes** [comment]
Link relative to home or the current repository (if any) ?

**Comment by plgitlogin** [comment]
The problem is the copid link should work in the pasted file.
if link in lib should be:    
     file any where => lib:/absolutepath
if link  in home/[id]/[repo]/absolutpath   should be :    
     if file  same repo    /absolutpath
     if file other repo    repo:/absolutpath
     else no copy 
 
if link in home/[id]/path no repo  
   if file in home/[id]/norepo       /path 
  else don't authorize copy 

This is no a priority (do ony if the copying is easy) else set this for another mile stone.

**Comment by mciissee** [comment]
already implemented with the new version of the editor
