### ISSUE TITLE
builder

### ISSUE THREAD

**Issue by nimdanor** [PremierLangage/premierlangage#70]
Forcer l'existance d'un builder est une mauvaise idée:
- cela consomme des ressources 
- beaucoup d'exercices n'en ont pas besoin.
je propose que l'on modifie le comportement : 
le builder ne seras appellé que si il y a la balise "builder"
en suite le programmeur du builder.py pourras choisir le nom de la balise contenant le code de build et comment appeler faire le traitement.

**Comment by plgitlogin** [comment]
Je trouve que cette solution est dégeulasse :


NONE_BUILDER = r"""
import sys, json, jsonpickle


if __name__ == "__main__":
    if len(sys.argv) < 3:
        msg = ("Sandbox did not call builder properly:\n"
               +"Usage: python3 builder.py [input_json] [output_json]")
        print(msg, file=sys.stderr)
        sys.exit(1)
    input_json = sys.argv[1]
    output_json = sys.argv[2]

    with open(input_json, "r") as f:
        dic = json.load(f)

    with open(output_json, "w+") as f:
        f.write(jsonpickle.encode(dic, unpicklable=False))

    sys.exit(0)

"""

**Comment by plgitlogin** [comment]
l'idée est de ne pas appeler le builder et non pas avoir un builder qui fait rien ....
je sais c'est pas la même chose il faut savoir si le pl a besoin d'un builder ou non ...
et donc il a des chose afaire ... mais appeller la sandbox pour qu'elle fasse rien c'est pas ECOLOGIQUE .

**Comment by qcoumes** [comment]
Il me semble que c'était surtout histoire d'envoyer l'environnement à la sandbox, afin de permettre l'évaluation.
