### ISSUE TITLE
import dans la sandbox 

### ISSUE THREAD

**Issue by plgitlogin** [PremierLangage/premierlangage#79]
le fichier sandboxio devrait être sur la sandbox et ne devrait pas être importé.

Dans le docker file il faut un dossier /var/lib/pl qui contient un clone de 
github.com/plgitlogin/sandbox-ressource
avec les fichiers que l'on souhaite inclure dans le PYTHONPATH du python3 qui est exécuté sur la sandbox .

**Comment by nimdanor** [comment]
The lib-standard-project is the place to discus this.
What files of standard-lib should be in the import path of the sandbox's python.
