### ISSUE TITLE
Git users description from pl-test

### ISSUE THREAD

**Issue by nborie** [PremierLangage/premierlangage#86]
Hello,

When I am logged in moodle(and PL) as nborie and I add locals modif --> commit --> push on my personnal repository Cbank : https://github.com/nborie/Cbank/commits/master  (all that from pl-test servor using the graphical interface for contributing), one can see that my name become DR (I use nborie as login and my personnel github password)...

Strange ? Bug ?

**Comment by qcoumes** [comment]
Definitely a bug

**Comment by nborie** [comment]
Just a small comment...

When I commit/push from pl-test to the nborie/Cbank repo, my name become dr.
This 19th november, I did commit/push from pl.u-pem.fr to Cbank and my name was www-data.

Everytimes commits/pushes did work... And I really don't care to the name given... Anyway, it stay a small priority bug....

**Comment by nborie** [comment]
This bug is still on very low priority (I really don't care about any name given automatically....). Anyway, perhaps the following log could help to fix this very small bug..

As I was creating a new repository and when I tried to do the very first commit on this new repository, i did get the following message 
***********************************************
DATE : 14 january 2018
URL : https://pl.u-pem.fr/filebrowser/home/OSbank/exercises/MCQ/generalities/
***********************************************
[master 81e39cb] First commit with MCQ structuration
 Committer: www-data <www-data@pl.u-pem.fr>
Votre nom et votre adresse e-mail ont été configurés automatiquement en se
fondant sur votre nom d'utilisateur et le nom de votre machine. Veuillez 
vérifier qu'ils sont corrects. Vous pouvez supprimer ce message en les 
paramétrant explicitement. Lancez les commandes suivantes et suivez les
instruction dans votre éditeur pour éditer votre fichier de configuration :

    git config --global --edit

Après ceci, vous pouvez corriger l'identité utilisée pour cette validation avec :

    git commit --amend --reset-author

 1 file changed, 1 insertion(+)
 create mode 100644 exercises/MCQ/generalities/questions.py
