### ISSUE TITLE
New Mardkown app

### ISSUE THREAD

**Issue by qcoumes** [PremierLangage/premierlangage#89]
We need a **new app for processing Markdown**, currently, [django-markdown](https://github.com/klen/django_markdown) is used and seems no longer maintained.

The main problem is that django-markdown **conflict with indentated HTML** and does **not allow syntax highlight**.

The best solution would be to use a Markdown app that only process backquoted text as code, not indentated one, and allow syntax highlight through ***```[LANG]*** .

It could be usefull if the app also provide some kind of **django template tag** (like `{% text|markdown %}`) allowing to process markdown in django's template, even though we could easily write such template if necessary.

**Comment by qcoumes** [comment]
https://github.com/neutronX/django-markdownx Seems like a good alternative

**Comment by nimdanor** [comment]
Ok on ajoute cela à la version de Noel.

**Comment by mciissee** [comment]
http://demo.showdownjs.com seems to be a good solution @nimdanor

**Comment by niotie** [comment]
Why is this issue closed? Do we have access to a new Markdown processor ? 

I would really love to be able to write
```python
print("it lives!")
```
and, let's be crazy, `print("it lives!")`{.python} in my exercises. So if it already works, i want to know!
