### ISSUE TITLE
A moto for premierlangage

### ISSUE THREAD

**Issue by nborie** [PremierLangage/premierlangage#93]
We don't have a final name for the premierlangage project but could we set a moto, a goal, a long term aim... For example, Sage has for moto : Mission: Creating a viable free open source alternative to Magma, Maple, Mathematica and Matlab.

So please, what is our mission ? This can be said with 1(best), 2 or 3 lignes at most...

My proposition : 
* Developer une plate forme intelligente d'exercices en ligne multi-matière

This is short and the adjective "intelligente" is hiding a lot of stuff... This is, one more time, very commercial but we need to structure our speech on what we are doing!

**Comment by nborie** [comment]
This goal will be written in bold on the web front page of the project ! It has thus some importance.

**Comment by nimdanor** [comment]
Smart online multipurpose/general/interactive exercising
plateform/software/tool Soge(p/s/t)
une plate forme intelligente d'exercices en ligne multi-disciplinaire


Le lun. 15 oct. 2018 à 13:08, Nicolas Borie <notifications@github.com> a
écrit :

**Comment by nthiery** [comment]
Smart/Intelligent are rather uninformative buzz words.

Versatile? Extensible? Flexible? Modular? Easy to use and extend?

**Comment by Pavell94000** [comment]
"Par les profs, pour les profs"
@nborie

**Comment by qcoumes** [comment]
So, any other idea or should we now use "By teachers, for teachers" ?

@nborie  @nimdanor @nthiery @ddoyen

**Comment by plgitlogin** [comment]
or

For teachers by teachers !

Pour des prof par des profs (avec l'argot en prime )

Le 09/12/2018 à 10:10, Coumes Quentin a écrit :
> By teachers, for teachers

**Comment by plgitlogin** [comment]
The PL plate-form a teaching tool, For teachers by teachers !

**Comment by esandier** [comment]
The open engine which can power any e-learning project.

**Comment by nborie** [comment]
Let's close this old ticket....

For information, several motos has been chosen :
* PLaTon, Platform for Learning and Teaching online.
* Dis-moi et j'oublierai, montre-moi et je me souviendrai, implique-moi et je comprendrai.
* For teachers by teachers !
* Un outil pour apprendre et pour enseigner.
